text_pt = {
    "PERIGO: Todas as características neste script são consideradas arriscadas. Existe a possibilidade de que sua conta seja suspensa por um número desconhecido de dias (as suspensões são aleatórias). Você foi avisado.",
    "Tentando transferir dinheiro para o banco",
    "Por favor, considere desativar a função para evitar bans",
    "Continuando o loop",
    "Segundos decorridos:",
    "Dinheiro ganho: R$",
    "Dinheiro por hora: R$",
    "Dinheiro por minuto: R$",
    "Dinheiro por segundo: R$",
    "Opções de segurança",
    "Algumas opções que recomendo que você ative ;)",
    "Opções para Controlar Lucros",
    "Ferramentas de trapaça",
    "Muito útil para quem deseja trapacear na conta",
    "Transações limitadas",
    "São transações que só podem ser realizadas uma vez",
    "Habilitar sobreposição",
    "Habilitar tudo abaixo",
    "Mostrar tempo decorrido",
    "Mostrar ganhos totais",
    "Mostrar ganhos por hora",
    "Mostrar ganhos por minuto",
    "Mostrar ganhos por segundo",
    "Selecionar cor",
    "Selecione uma cor para o texto",
    "Opções rápidas ;)",
    "Loop de 1 milhão [RECOMENDADO] [SEGURO]",
    "Fornece 1 milhão a cada segundo até desativar esta função",
    "Transferir dinheiro automaticamente",
    "Funcionará de acordo com os valores atribuídos para detectar e transferir",
    "Dinheiro transferido com sucesso :)",
    "Valor a ser detectado",
    "Digite o valor que deseja ser detectado para começar a salvar automaticamente\nNota: o valor inicial é metade do seu dinheiro atual",
    "Valor a ser transferido",
    "Digite o valor que deseja salvar no banco automaticamente\nNota: o valor inicial será o dinheiro que você possui atualmente",
    "Você não pode transferir um valor que não possui",
    "Isso levará cerca de 30 segundos. :)", --função op100mxd
    "Iniciando em 3.",
    "Iniciando em 2.",
    "Iniciando em 1.",
    "Operação concluída. ;)",
    "Se a operação não atingiu ´x´ milhões, use a função de loop de 1 milhão",
    "A função já foi executada. :/",
    "Trapaça [100 MILHÕES] [AUTOMÁTICO]",
    "Disponível apenas uma vez por conta (recomendado) \nNota: Comece com duas transações de 15 milhões e depois complete com transações de 1 milhão",
    "Executando bealone para mais segurança ;)",
    "Transferir todo o seu dinheiro",
    "Transfira todo o seu dinheiro atual para o banco",
    "Dinheiro transferido com sucesso :)",
    "Repetidor de loop",
    "Selecione a quantidade de iterações para o loop de 1 milhão (máximo 500)",
    "Valor a ser recebido: ",
    "Loop 1 MILHÃO [POR ITERAÇÕES]",
    "Funcionará de acordo com a quantidade de iterações selecionadas acima",
    "Executando bealone para mais segurança ;)",
    "Operação concluída. ;)\nValor total recebido: ",
    "Editor de K/D",
    "Edite o K/D.",
    "Loop de 40 milhões [Lento] [NÃO SEGURO]",
    "Atualmente detectado (eu acho)\nSe eu fosse você, não usaria",
    "Loop de 5K [Fichas]",
    "Você realmente vai usar isso? :/",
    "Bloquear erros de transação",
    "Recomendo ativar para evitar qualquer tipo de erro ;)",
    "Configurações otimizadas",
    "Esperamos que maximize seu TPS e FPS :)",
    "Informações de trapaça",
    "Tem dúvidas de como está indo?",
    "Quanto dinheiro posso fazer?",
    "Pelo menos 100 milhões a cada 2 horas\nNota: Não seja muito ganancioso.",
    "Posso depositar bilhões com segurança?",
    "Embora não seja recomendado, a resposta é sim, tudo dependerá da frequência com que você deposita o dinheiro",
    "Existe risco de banimento?",
    "Com certeza! Tudo depende da quantidade de dinheiro que você decidiu depositar\nNota: as suspensões são aleatórias, geralmente você é banido por 30 dias",
    "Quais são os valores testados?",
    "1 MILHÃO-50 MILHÕES [Seguro]\n50 MILHÕES-100 MILHÕES [Seguro]\n100M-1 BILHÃO [Seguro]\n1B-5 Bilhões [Seguro]\n5B-7B [Pouco seguro]\n7B+ [BANÍVEL] [30 DIAS]",
    "KD Atual", --adicionado a partir daqui
    "Kills Atuais: ",
    "Mostra suas kills atuais.",
    "Mortes Atuais: ",
    "Mostra suas mortes atuais.",
    "Ratio Atual: ",
    "Mostra sua taxa atual.",
    "Novo K/D",
    "Novo Valor de Kills",
    "Selecione um novo valor de kills.",
    "Novo Valor de Mortes",
    "Selecione um novo valor de mortes.",
    "Nova Taxa: ",
    "Mostra seu novo K/D.",
    "Mudar K/D",
    "Substitui o K/D atual pelo modificado.",
    "Seu K/D mudou para: ",
    "Kills Atuais: ",
    "Mortes Atuais: ",
    "Ratio Atual: ",
    "Nova Taxa: ",
    "Você precisa estar online!",
    "~p~Carregado ~r~",
    " ~p~;)\n~p~Oi! ~o~",
    "\n~p~Nós trapaceamos sua conta ~g~$$$ ~p~ou o quê ~p~? ;)",
    "Removedor de Dinheiro",--adicionado
    "Excedeu milhões? Aqui está a solução \nNota: Ajuste o valor a ser removido, Até $2B!",
    "Valor a ser Removido: ",
    "Um equipamento balístico será implantado, não se preocupe",
    "Remover Seu Dinheiro",
    "A quantidade de dinheiro ajustada acima será removida",
    "Operação concluída. ;)\nValor total removido: ",
    "Esta chave pertence a outro usuário :/",
    "A chave está incorreta. Tente novamente.",
    "Inserir Chave",
    "Digite a chave para desbloquear o script",
    "Chave correta! Script desbloqueado.",
    "Opções de Transferência de Dinheiro",
    "Opções de Retirada de Dinheiro",
    "Opções Extras",
    "500k em um clique",
    "750k em um Clique",
    "Observação: Use apenas uma vez por dia.",
    "Trapaça [100 MILHÕES] [AUTOMÁTICO]",
    "Trapaça [100 MILHÕES] [AUTOMÁTICO]",
    "Trapaça [100 MILHÕES] [AUTOMÁTICO]",
    "Por favor, selecione um valor válido",
    "Loop de 50k",
    "Fornece 50k por segundo",
    "Loop de 10 Milhões",
    "Fornece 10 Milhões por segundo",
    "10 Milhões com Um Clique",
    "Fornece 10 milhões com um clique (É recomendado não abusar, caso contrário não funcionará)",
    "20 Milhões com Um Clique",
    "Fornece 20 milhões com um clique (É recomendado não abusar, caso contrário não funcionará)",
    "Eliminar Todo o Seu Dinheiro",
    "Deixa-o com 1$",
    "Opções De Um Clique ;)",
    "ir para a lista de jogadores", --ultimate_drop
    "Mensagens",
    "Método Roleta",
    ">> Se você quer ganhar dinheiro, venha ao cassino, jogue roleta e aposte o máximo na primeira dúzia (50k) e no Vermelho 1 (5k), ganha 3, perde 1, 550k por minuto.",
    ">> Se você quer ganhar dinheiro, venha ao cassino, jogue blackjack. Clique na aposta máxima, depois escolha 'manter' e ganhe o dobro da sua aposta.",
    "Método Roleta Desativado",
    "Notifica que o método foi desativado",
    ">> O método para ganhar dinheiro no cassino foi desativado :)",
    "Nova Implementação",
    "Opções de Ultimate Drops",
    "Lista de Drops",
    "Ultimate Drops",
    "Opções de Spawn [Geral]",
    "Drop de Dinheiro",
    "Drop de Dinheiro [LOCAL]",
    "Drop de Dinheiro [ONLINE]",
    "Drop de Armas",
    "Drop de Munição",
    "Drop de Saúde e Armadura",
    "Drop de Diversos",
    "Opções de Spawn",
    "Opções de Overlay",
    "Dinheiro Total Doado: $",
    "Mostrar Dinheiro Doado",
    "Ativar ou desativar informação do dinheiro total doado",
    "Munição Total Doada: ",
    "Mostrar Munição Doada",
    "Ativar ou desativar informação da munição total doada",
    "Armas Totais Doadas: ",
    "Mostrar Armas Doadas",
    "Ativar ou desativar informação das armas totais doadas",
    "Saúde e Armadura Totais Doadas: ",
    "Mostrar Saúde e Armadura Doadas",
    "Ativar ou desativar informação da saúde e armadura totais doadas",
    "Diversos Totais Doados: ",
    "Mostrar Diversos Doados",
    "Ativar ou desativar informação dos diversos totais doados",
    "Resetar Todos os Valores",
    "Redefinir todos os totais doados para '0'",
    "Delay de Spawn",
    "Ajustar tempo de espera para drop.\nNota: Isso não afetará a opção 'Chuva de Dinheiro'",
    "Ajustar Valor 'X'",
    "Ajustar posição de drop\nNota: Isso não afetará a opção 'Chuva de Dinheiro'",
    "Ajustar Valor 'Y'",
    "Ajustar Valor 'Z'",
    "Ajustar altura de drop\nNota: Isso não afetará a opção 'Chuva de Dinheiro'\nSe configurado para '0' o valor será 1.5",
    "Dando Dinheiro para ",
    "Chuva de Dinheiro [ONLINE]",
    "Drop de Dinheiro [Aleatório]",
    "Dá 8 tipos de drops de dinheiro aleatoriamente para a pessoa selecionada",
    "Drop de Dinheiro [ONLINE] 1",
    "Drop de Dinheiro [ONLINE] 2",
    "(sem delay) (valor fixo)",
    "Isso dá RP e Dinheiro para outros jogadores",
    "Drop Aleatório 5k $ 1K RP",
    "Você pode usar esta opção infinitamente",
    "Drop 75k e RP (Funciona apenas a cada 24 horas)",
    "(Funciona apenas a cada 24 horas)",
    "Drop 100k e RP",
    "Opções de Spawn",
    "Valor do Dinheiro",
    "Ajustar valor do dinheiro para drop",
    "Chuva de Dinheiro [LOCAL]",
    "SÓ FUNCIONA PARA VOCÊ",
    "Dropar Tudo",
    "Somente Local",
    "Valor da Munição",
    "Ajustar valor para drop",
    "Ativar Aleatorização",
    "Se ativado, o valor da munição gerada será 2000, 1900, 1616, 1500, 666, 500, 100.",
    "Valor para 1000",
    "Ativar isso se você quiser que o valor da munição recebida mude para 1000",
    "Valor de Spawn",
    "Ajustar valor do drop.\nNota: O valor padrão é 100%",
    "Delay Aleatório",
    "Se ativado, o tempo de spawn será aleatório.",
    "Saúde",
    "Lanche P's & Q's",
    "Armadura",
    "Paraquedas",
    "Loops de RP",
    "Parar no Nível",
    "Delay do Loop",
    "Ativar Loop",
    "Já está no nível",
    "Dinheiro[Método Cassino]",
    "Ganhar Dinheiro [CASSINO]",
    "Disparar Dinheiro [Local]",
    "Disparar Dinheiro [ONLINE]",
    "Disparar Munição",
    "Disparar Armas",
    "Selecione qual arma disparar",
    "selecione apenas uma arma",
    "Disparar Arma Selecionada",
    "Lembre-se de selecionar uma arma primeiro :)",
    "Disparar Saúde e Armadura",
    "Disparar Diversos",
    "Limpado, Adeus <3",
    "(Funciona apenas a cada 24 horas)",
    "[SafeMoneyLua]: Erro inesperado. Por favor, entre em contato com o provedor. \n Código de erro: 236",
    "Atraso de 10 minutos",
    "Atraso de 30 minutos",
    "Atraso aleatório entre 2 a 10 segundos",
    "Loop de 180k [Risky] [A]",
    "Habilitar quantidade aleatória",
    "Funciona para opções simbolizadas com '[A]'",
    "Ajustar quantidade de dinheiro a receber",
    "Loop de atraso aleatório",
    "Ajustar atraso do loop",
    "Funciona para opções simbolizadas com '[A]'\nExpressa em milissegundos",
    "Quantia ajustável \nQuantia máxima ",
    "Configurações de Dinheiro",
    "Cobrar Tudo [APENAS UMA VEZ POR DIA]",
    "Lista de Dinheiro",
    "Seleccionar tipo de dinero",
"Habilitar dinero de vehículos",
"Actualizar tabla de vehículos",
"Laboratório de Ácido",
"Reabastecer Suprimentos",
"Velocidade de Produção",
"15K Valor Por Unidade",
"Máximo de Unidades 160",
"Opções do Hangar",
  "Preço Máximo Por Caixa [500K]",
  "Remover Parte do Ron",
    "Remover Atraso de Espera",
    "Venda Instantânea",
    "Somente Entrega Aérea",
    "Classic Heist [15M]",
"Opções de Heist 15M",
"Opções Extras",
"Como Usar",
"1) Primeiro desbloqueie o golpe que você deseja fazer. \n2) Inicie a missão sozinho, pule a cinemática e quando estiver no quadro de planejamento, selecione a opção de completar a preparação. \n3) Inicie o golpe, convide seus amigos e no quadro de planejamento escolha o preset que você deseja. \n4) Uma vez que o golpe tenha iniciado, selecione a opção de finalizar instantaneamente.",
"Presets",
"Todos Recebem 15M",
"Só Você Não Recebe 15M",
"Remover Cooldown",
"Completar Todas as Configurações",
"Parece que você não está em nenhum apartamento no momento.",
"O quadro de planejamento do golpe não pôde ser encontrado neste apartamento. Certifique-se de estar em um dos apartamentos de alto padrão.",
"Permitir Jogar Sozinho",
"Forçar Pronto",
"Faça todos os jogadores estarem prontos forçadamente no quadro de planejamento.",
"Desbloquear Todos os Heists Clássicos",
"Dinheiro Diverso",
"Opção habilitada, seu dinheiro total atual é de $",
"\nNota: os reembolsos serão aplicados apenas para compras de até 15M\n~r~Você deve esperar 20 minutos após cada reembolso para que funcione novamente.",
"Reembolso de compra",
"Detecta se você faz uma compra e reembolsa automaticamente o que você gastou.\nNota: Somente para compras de até 15M",
"[SAFEMONEYLUA]\nUm gasto de $",
" foi detectado e reembolsado com sucesso para sua conta de carteira ;)",
"Sua compra ultrapassa 15M, infelizmente, não poderemos reembolsá-lo :/",
"[SAFEMONEYLUA]\n~r~Você precisa esperar ",
" ~r~mais minutos para que o próximo reembolso funcione.",
"[SAFEMONEYLUA]\nFoi detectado um gasto de $",
 " \nTentaremos reembolsar porque ~r~você desativou o tempo de espera de 20 minutos :/",
"[SAFEMONEYLUA]\nParece que isso não funcionou :/",
"[SAFEMONEYLUA]\nVocê foi reembolsado $",
" ~g~com sucesso :)",
"Ignorar tempo sugerido",
"Ignore o tempo de 20 minutos estabelecido no script\nNota: Isso pode levar a que algumas compras não sejam devolvidas corretamente",



}

text_es = {
    "PELIGRO: Todas las características en este script se consideran arriesgadas. Existe la posibilidad de que tu cuenta sea suspendida en un número desconocido de días (las suspenciones se retrasan al azar). Has sido advertido.",
    "Intentando transferir el dinero al banco",
    "Por favor, considera desactivar la función para evitar baneos",
    "Continuando con el loop",
    "Segundos Transcurridos: ",
    "Dinero Ganado: $",
    "Dinero/Hora: $",
    "Dinero/Minuto: $",
    "Dinero/Segundo: $",
    "Opciones de Seguridad",
    "Algunas opciones que te recomiendo que consideres activar ;)",
    "Opciones Para Controlar Ganancias",
    "Herramientas Para Cheteos",
    "Bastante util para personas que desean chetar su cuenta",
    "Transacciones limitadas",
    "Son transacciones que solo se pueden realizar una sola vez",
    "Habilitar superposición",
    "Habilita Todo Lo De Abajo",
    "Visualizar Tiempo Transcurrido",
    "Visualizar Ganancias Totales",
    "Visualizar Ganancias por Hora",
    "Visualizar Ganancias por Minuto",
    "Visualizar Ganancias por Segundo",
    "Seleccionar Color",
    "Seleccione un color para el texto",
    "Opciones Rápidas ;)",
    "Loop De 1 Millón [RECOMENDADO] [SEGURO]",
    "Te otorga 1 millón cada segundo hasta que desactives esta función",
    "Transferir tu dinero automáticamente",
    "Funcionará acorde a los valores asignados en monto a detectar y transferir",
    "Dinero transferido con éxito :)",
    "Monto a Detectar",
    "Ingresa el valor que quieres que se detecte para que empiece a guardar automáticamente\nNota: el valor inicial es la mitad de tu dinero actual",
    "Monto a Transferir",
    "Ingresa el valor que quieras guardar al banco automáticamente\nNota: el valor inicial será el dinero que poseas actualmente",
    "No puedes trasferir un monto que no posees",
    "Esto tomará alrededor de 30 segundos. :)", --funcion op100mxd
    "Iniciando en 3.",
    "Iniciando en 2.",
    "Iniciando en 1.",
    "Operación completada. ;)",
    "Si la operación no alcanzó los ´x´ Millones, utiliza la función de loop de 1 millon",
    "La función ya se ha ejecutado. :/",
    "Cheteo [100 MILLONES] [AUTOMÁTICO]",
    "Solo disponible una vez por cuenta (es lo recomendable) \nNota: Primero inicia con dos transacciones de 15 Millones y luego los completa con transacciones de 1 Millón",
    "Ejecutando bealone para más seguridad ;)",
    "Transferir todo tu dinero",
    "Transfiere todo tu dinero actual al banco",
    "Dinero Transferido con éxito :)",
    "Repetidor de Loop",
    "Selecciona la cantidad de iteraciones para el loop de 1 millón (máximo 500)",
    "Monto a Recibir: ",
    "Loop 1 MILLON [POR ITERACIONES]",
    "Funcionará de acuerdo a la cantidad de iteraciones que seleccionaste arriba",
    "Ejecutando bealone para más seguridad ;)",
    "Operación completada. ;)\nMonto total recibido: ",
    "Editor de K/D",
    "Edita el K/D.",
    "Loop De 40 Millones [Lento] [NO SEGURO]",
    "Detectado Actualmente (creo)\nSi yo fuera tú no lo usaría",
    "Loop de 5K [Fichas]",
    "¿De Verdad Vas a Usar Esto? :/",
    "Bloquear Errores de Transacción",
    "Te lo recomiendo activar para evitar cualquier tipo de error ;)",
    "Configuraciones Optimizadas",
    "Esperamos que maximice tu TPS y FPS :)",
    "Informacion de los cheteos",
    "Tienes dudas de como va la cosa?",
    "Cuanto Dinero puedo hacer?",
    "Al menos 100 millones cada 2 horas\nNota: Tampoco seas avaricioso.",
    "Puedo meterme billones de manera segura?",
    "Aunque no es recomendable, la respuesta es que sí, todo dependerá de la frecuencia en que te metes el dinero",
    "Existe riesgo de baneo?",
    "Claro que sí! Todo dependerá de la cantidad de dinero que decidiste meter\nNota: las suspensiones son al azar, generalmente te banean por 30 días",
    "Cuales son los montos testeados?",
    "1 MILLON-50 MILLONES [Seguro]\n50 MILLONES-100 MILLONES [Seguro]\n100M-1 BILLON [Seguro]\n1B-5 Billones [Seguro]\n5B-7B [Poco seguro]\n7B+ [BANEABLE] [30 DÍAS]",
    "KD Actual", --añadido desde aqui
    "Kills Actuales: ",
    "Muestra Tus Kills actuales.",
    "Muertes Actuales: ",
    "Muestra tus muertes actuales.",
    "Ratio Actual: ",
    "Muestra tu ratio actual.",
    "Nuevo K/D",
    "Nuevo Valor de Kills",
    "Selecciona un nuevo valor de kills.",
    "Nuevo Valor de Muertes",
    "Selecciona un nuevo valor de muertes.",
    "Nuevo Ratio: ",
    "Muestra tu nuevo K/D.",
    "Cambiar K/D",
    "Reemplaza el K/D Actual por el modificado.",
    "Tu K/D cambió a: ",
    "Kills Actuales: ",
    "Muertes Actuales: ",
    "Ratio Actual: ",
    "Nuevo Ratio: ",
    "Necesitas estar online!",
    "~p~Cargado ~r~",
    " ~p~;)\n~p~Hola! ~o~",
    "\n~p~Te Chetamos Tu Cuenta ~g~$$$ ~p~o que ~p~? ;)",
    "Removedor de Dinero",--añadido
    "Te excediste de millones? Aquí está la solución \nNota: Ajusta el valor a remover, Hasta $2B!",
    "Monto a Remover: ",
    "Se desplegará un equipo balístico, No te alarmes",
    "Remover Tu Dinero",
    "Se removera la cantidad de dinero ajustada arriba",
    "Operación completada. ;)\nMonto total removido: ",
    "Esta clave pertenece a otro usuario :/",
    "La clave es incorrecta. Inténtalo de nuevo.",
    "Ingresar Clave",
    "Ingresa la clave para desbloquear el script",
    "¡Clave correcta! Script desbloqueado.",
    "Opciones de Transferir Dinero",
    "Opciones de Remover Dinero",
    "Opciones Extra",
    "500k en un Click",
    "750k en un Click",
    "Nota: Utilizar solo una vez al dia.",
    "Cheteo [50 MILLONES] [AUTOMÁTICO]",
    "Cheteo [30 MILLONES] [AUTOMÁTICO]",
    "Cheteo [15 MILLONES] [AUTOMÁTICO]",
    "Por favor, seleccione un monto válido",
    "Loop De 50k",
    "Te otorga 50k por segundo",
    "Loop De 10 Millones",
    "Te otorga 10 Millones por segundo",
    "10 Millones En Un Click",
    "Te da 10 millones con un click (Se recomienda no abusar, de lo contrario no funcionará)",
    "20 Millones En Un Click",
    "Te da 20 millones con un click (Se recomienda no abusar, de lo contrario no funcionará)",
    "Eliminar Todo Tu Dinero",
    "te deja con 1$",
    "Opciones De Un Clic",
    "ir a lista de jugadores", --ultimate_drop
    "Mensajes",
    "Método Ruleta",
    ">> Si quieres ganar dinero, ven al casino, juega a la ruleta y apuesta al máximo en el primer grupo de 12 (50k) y al Rojo 1 (5k), gana 3, pierde 1, 550k por minuto.",
    ">> Si quieres ganar dinero, ven al casino, juega al blackjack. Haz clic en la apuesta máxima, luego elige ´mantener´ y gana el doble de tu apuesta.",
    "Método Ruleta Desactivado",
    "Notifica que el método fue desactivado",
    ">> El Método de ganar dinero en el casino fue desactivado :)",
    "Nueva Implementación",
    "Ultimate Drops Options",
    "Lista de Drops",
    "Ultimate Drops",
    "Opciones de Spawn [General]",
    "Money Drop",
    "Money Drop [LOCAL]",
    "Money Drop [Online]",
    "Drop Armas",
    "Drop Municion",
    "Salud Y Armadura Drop",
    "Misc Drop",
    "Opciones De Spawn",
    "Opciones De Overlay",
    "Dinero Total Donado: $",
    "Mostrar Dinero Donado",
    "Habilita o deshabilita la informacion del dinero total donado",
    "Total De Municion Donado: ",
    "Mostrar Municion Donada",
    "Habilita o deshabilita la informacion de la municion total donada",
    "Total De Armas Donadas: ",
    "Mostrar Armas Donadas",
    "Habilita o deshabilita la informacion del total de armas donadas",
    "Total De Salud Y Armadura Donadas: ",
    "Mostrar Salud Y Armaduras Donadas",
    "Habilita o deshabilita la informacion de la Armadura y Salud total donado",
    "Total De ´Otros´ Donados: ",
    "Mostrar ´Otros´ Donados",
    "Habilita o deshabilita la informacion del total de ´otros´ donados",
    "Reiniciar Todos Los Valores",
    "Reestablece a un valor de ´0´ toda la informacion de los totales donados",
    "Delay de spawn",
    "Ajusta el tiempo de espera para dropear.\nNota: Esto no afectará a la opcion de 'Lluvia de Dinero'",
    "Ajuste Valor ´X´",
    "Ajusta la posicion a dropear\nNota: Esto no afectará a la opcion de 'Lluvia de Dinero'",
    "Ajuste Valor ´Y´",
    "Ajuste Valor ´Z´",
    "Ajusta la altura a dropear\nNota: Esto no afectará a la opcion de 'Lluvia de Dinero'\nSi se encuentra en un valor de ´0´ el valor será de 1.5",
    "Dando Dinero a ",
    "Lluvia de dinero [ONLINE]",
    "Money Drop [Aleatorio]",
    "Da 8 tipos de money drop de forma aleatoria para la persona seleccionada",
    "Money Drop [ONLINE] 1",
    "Money Drop [ONLINE] 2",
    "(no delay) (fixed amount)",
    "This Gives RP and Money to other players",
    "Drop Random 5k $ 1K RP",
    "Puedes usar esta opcion infinitas veces",
    "Drop 75k y RP (Solo funciona cada 24hs)",
    "(Solo funciona cada 24hs)",
    "Drop 100k y RP",
    "Opciones de Spawn",
    "Valor del dinero",
    "Ajusta el monto del dinero a dropear",
    "Lluvia de Dinero [LOCAL]",
    "SOLO FUNCIONA PARA TI",
    "Dropear Todo",
    "Solo Local",
    "Valor de la Municion",
    "Ajusta el valor a dropear",
    "Habilitar Aleatorización",
    "Si habilitas esto el valor de la municion generada sera de 2000, 1900, 1616, 1500, 666, 500, 100.",
    "Valor A 1000",
    "Activa esto si quieres que el valor de la municion recibida cambie a 1000",
    "Valor de spawn",
    "Ajusta el valor del drop.\nNota: El valor por defecto es de 100%",
    "Delay Random",
    "Si habilitas esto el tiempo de spawn sera aleatorio.",
    "Salud",
    "P's & Q's Snack",
    "Armadura",
    "Paracaídas",
    "RP Loops",
    "Parar en el Nivel",
    "Delay del Loop",
    "Habilitar Loop",
    "Ya está en el nivel",
    "Dinero[Metodo Casino]",
    "Ganar Dinero [CASINO]",
    "Disparar Dinero [Local]",
    "Disparar Dinero [ONLINE]",
    "Disparar Munición",
    "Disparar Armas",
    "Selecciona qué arma disparar",
    "solo selecciona un arma",
    "Disparar Arma Seleccionada",
    "Recuerda seleccionar un arma primero :)",
    "Disparar Salud y Armadura",
    "Disparar Misc",
    "Limpiado, Adios <3",
    "(Solo funciona cada 24hs)",
    "[SafeMoneyLua]: Error inesperado. Porfavor comuniquese con el proveedor. \n Codigo error: 236",
    "Retraso de 10 minutos",
    "Retraso de 30 minutos",
    "Retraso aleatorio entre 2 a 10 segundos",
    "Loop de 180k [Risky] [A]",
    "Habilitar cantidad aleatoria",
    "Funciona para las opciones simbolizadas con '[A]'",
    "Ajustar cantidad de dinero a recibir",
    "Loop de retraso aleatorio",
    "Ajustar retraso del bucle",
    "Funciona para las opciones simbolizadas con '[A]'\nExpresado en milisegundos",
    "Monto ajustable \nMonto máximo ",
    "Ajustes de dinero",
    "Cobrar Todo [SOLO UNA VEZ AL DÍA]",
     "Lista de dinero",
     "Seleccionar tipo de dinero",
"Habilitar dinero de vehículos",
"Actualizar tabla de vehículos",
"Opciones de Laboratorio de Ácido",
"Rellenar Suministros",
"Velocidad de Producción [X10]",
"15K Valor Por Unidad",
"Máximo de Unidades 160",
"Opciones de Hangar",
"Precio Máximo Por Caja [500K]",
"Eliminar Parte de Ron",
"Eliminar Tiempo de Espera",
"Vender Instantaneamente",
"Solo por Entrega Aérea",
"Classic Heist [15M]",
"Opciones de Heist 15M",
"Opciones Extra",
"Cómo Usar",
"1) Primero desbloquea el golpe que quieras hacer. \n2) Inicia la misión en solitario, saltea la cinemática y cuando estés en el tablero de planeación selecciona la opción de completar preparación. \n3) Inicia el golpe, invita a tus amigos y en el tablero de planeación elige el preset que quieras. \n4) Una vez iniciado el golpe, selecciona la opción de finalizar instantáneamente.",
"Presets",
"Todos Reciben 15M",
"Sólo Tú No Recibes 15M",
"Eliminar Cooldown",
"Completar Todas las Preparatorias",
"Parece que actualmente no estás en ningún apartamento.",
"No se pudo encontrar el tablero de planificación del golpe en este apartamento. Asegúrate de estar en uno de los apartamentos de alto nivel.",
"Permitir Jugar Solo",
"Forzar Listo",
"Hacer que todos los jugadores estén listos forzosamente en el tablero de planificación.",
"Desbloquear Todos los Heists Clásicos",
"Dinero Variado",
"Opción habilitada, tu dinero total actual es de $",
"\nNota: los reembolsos se aplicarán solo para compras de hasta 15M\n~r~Debes esperar 20 minutos después de cada reembolso para que vuelva a funcionar.",
"Reembolsar Compras",
"Detecta si realizas una compra y automáticamente reembolsa lo que gastaste.\nNota: Solo para compras de hasta 15M",
"[SAFEMONEYLUA]\nSe detectó un gasto de $",
" y se reembolsó exitosamente a tu cuenta de billetera ;)",
"Tu compra supera los 15M, lamentablemente no podremos reembolsarte :/",
"[SAFEMONEYLUA]\n~r~Necesitas esperar ",
" ~r~más minutos para que el próximo reembolso funcione.",
"[SAFEMONEYLUA]\nSe detectó un gasto de $",
 " \nSe hará el intento de reembolsar debido a que ~r~desactivaste el tiempo de espera de 20 minutos :/",
"[SAFEMONEYLUA]\nAl parecer eso no funcionó :/",
"[SAFEMONEYLUA]\nSe te reembolsó $",
" ~g~de forma exitosa :)",
"Ignorar tiempo sugerido",
"Ignora el tiempo de 20 minutos establecido en el script\nNota: Esto puede conllevar a que algunas compras no se te devuelvan correctamente",





}


text_en = {
    "DANGER: All features in this script are considered risky. There is a possibility that your account may be suspended for an unknown number of days (suspensions are random). You have been warned.",
    "Attempting to transfer money to the bank",
    "Please consider deactivating the function to avoid bans",
    "Continuing with the loop",
    "Seconds Elapsed:",
    "Money Earned: $",
    "Money/Hour: $",
    "Money/Minute: $",
    "Money/Second: $",
    "Security Options",
    "Some options that I recommend you consider activating ;)",
    "Options to Control Profits",
    "Cheat Tools",
    "Quite useful for people who want to cheat on their account",
    "Limited Transactions",
    "These are transactions that can only be performed once",
    "Enable Overlay",
    "Enable All Below",
    "Show Elapsed Time",
    "Show Total Earnings",
    "Show Earnings per Hour",
    "Show Earnings per Minute",
    "Show Earnings per Second",
    "Select Color",
    "Select a color for the text",
    "Quick Options ;)",
    "Loop 1 Million [RECOMMENDED] [SAFE]",
    "Gives you 1 million every second until you disable this function",
    "Automatically transfer your money",
    "Will work according to the values assigned to detect and transfer",
    "Money transferred successfully :)",
    "Amount to Detect",
    "Enter the value you want to be detected to start saving automatically\nNote: the initial value is half of your current money",
    "Amount to Transfer",
    "Enter the value you want to save to the bank automatically\nNote: the initial value will be the money you currently have",
    "You cannot transfer an amount you do not have",
    "This will take about 30 seconds. :)", --op100mxd function
    "Starting in 3.",
    "Starting in 2.",
    "Starting in 1.",
    "Operation completed. ;)",
    "If the operation did not reach ´x´ million, use the 1 million loop function",
    "The function has already been executed. :/",
    "Cheat [100 MILLION] [AUTOMATIC]",
    "Only available once per account (recommended)\nNote: Start with two transactions of 15 million and then complete with transactions of 1 million",
    "Running bealone for more security ;)",
    "Transfer all your money",
    "Transfer all your current money to the bank",
    "Money transferred successfully :)",
    "Loop Repeater",
    "Select the number of iterations for the 1 million loop (maximum 500)",
    "Amount to Receive: ",
    "Loop 1 MILLION [BY ITERATIONS]",
    "Will work according to the number of iterations you selected above",
    "Running bealone for more security ;)",
    "Operation completed. ;)\nTotal amount received: ",
    "KD Editor",
    "Edit the K/D.",
    "40 Million Loop [Slow] [NOT SAFE]",
    "Currently Detected (I think)\nIf I were you, I wouldn't use it",
    "5K Loop [Chips]",
    "Are you really going to use this? :/",
    "Block Transaction Errors",
    "I recommend activating it to avoid any kind of error ;)",
    "Optimized Settings",
    "We hope it maximizes your TPS and FPS :)",
    "Cheat Information",
    "Do you have doubts about how things are going?",
    "How much money can I make?",
    "At least 100 million every 2 hours\nNote: Don't be too greedy either.",
    "Can I safely enter billions?",
    "Although not recommended, the answer is yes, it will all depend on how often you enter the money",
    "Is there a risk of a ban?",
    "Sure! It all depends on the amount of money you decided to enter\nNote: suspensions are random, usually you are banned for 30 days",
    "What are the tested amounts?",
    "1 MILLION-50 MILLION [Safe]\n50 MILLION-100 MILLION [Safe]\n100M-1 BILLION [Safe]\n1B-5 Billion [Safe]\n5B-7B [Not very safe]\n7B+ [BANABLE] [30 DAYS]",
    "Current KD", --added from here
    "Current Kills: ",
    "Show your current kills.",
    "Current Deaths: ",
    "Show your current deaths.",
    "Current Ratio: ",
    "Show your current ratio.",
    "New KD",
    "New Kills Value",
    "Select a new kills value.",
    "New Deaths Value",
    "Select a new deaths value.",
    "New Ratio: ",
    "Show your new KD.",
    "Change KD",
    "Replace the Current KD with the modified one.",
    "Your KD changed to: ",
    "Current Kills: ",
    "Current Deaths: ",
    "Current Ratio: ",
    "New Ratio: ",
    "You need to be online!",
    "~p~Loaded ~r~",
    " ~p~;)\n~p~Hello! ~o~",
    "\n~p~We cheat your account ~g~$$$ ~p~or what ~p~? ;)",
    "Money Remover",--added
    "Exceeded millions? Here's the solution \nNote: Adjust the value to be removed, Up to $2B!",
    "Amount to Remove: ",
    "A ballistic team will be deployed, don't be alarmed",
    "Remove Your Money",
    "The amount of money adjusted above will be removed",
    "Operation completed. ;)\nTotal amount removed: ",
    "This key belongs to another user :/",
    "The key is incorrect. Try again.",
    "Enter Key",
    "Enter the key to unlock the script",
    "Correct key! Script unlocked.",
    "Money Transfer Options",
    "Money Removal Options",
    "Extra Options",
    "500k one Click",
    "750k one Click",
    "Note: Use only once a day.",
    "Cheat [50 MILLION] [AUTOMATIC]",
    "Cheat [30 MILLION] [AUTOMATIC]",
    "Cheat [15 MILLION] [AUTOMATIC]",
    "Please select a valid amount",
    "50k Loop",
    "Grants you 50k per second",
    "10 Million Loop",
    "Grants you 10 million per second",
    "10 Million In One Click",
    "Gives you 10 million with one click (Abusing is not recommended, otherwise it won't work)",
    "20 Million In One Click",
    "Gives you 20 million with one click (Abusing is not recommended, otherwise it won't work)",
    "Delete All Your Money",
    "Leaves you with 1$",
    "One-Click Options ;)",
    "go to player list",--ultimate_drop
    "Messages",
    "Roulette Method",
    ">> If you want to make money, come to the casino, play roulette, and bet the maximum on the first dozen (50k) and Red 1 (5k), win 3, lose 1, 550k per minute.",
    ">> If you want to make money, come to the casino, play blackjack. Click on the maximum bet, then choose 'hold' and win double your bet.",
    "Roulette Method Disabled",
    "Notifies that the method was disabled",
    ">> The method to make money in the casino was disabled :)",
    "New Implementation",
    "Ultimate Drops Options",
    "Drops List",
    "Ultimate Drops",
    "Spawn Options [General]",
    "Money Drop",
    "Money Drop [LOCAL]",
    "Money Drop [ONLINE]",
    "Weapon Drop",
    "Ammo Drop",
    "Health and Armor Drop",
    "Misc Drop",
    "Spawn Options",
    "Overlay Options",
    "Total Money Donated: $",
    "Show Donated Money",
    "Enable or disable total donated money info",
    "Total Ammo Donated: ",
    "Show Donated Ammo",
    "Enable or disable total donated ammo info",
    "Total Weapons Donated: ",
    "Show Donated Weapons",
    "Enable or disable total donated weapons info",
    "Total Health and Armor Donated: ",
    "Show Donated Health and Armor",
    "Enable or disable total donated health and armor info",
    "Total 'Misc' Donated: ",
    "Show Donated 'Misc'",
    "Enable or disable total donated 'misc' info",
    "Reset All Values",
    "Reset all donated totals to '0'",
    "Spawn Delay",
    "Adjust drop wait time.\nNote: This will not affect the 'Money Rain' option",
    "Adjust 'X' Value",
    "Adjust drop position\nNote: This will not affect the 'Money Rain' option",
    "Adjust 'Y' Value",
    "Adjust 'Z' Value",
    "Adjust drop height\nNote: This will not affect the 'Money Rain' option\nIf set to '0' the value will be 1.5",
    "Giving Money to ",
    "Money Rain [ONLINE]",
    "Money Drop [Random]",
    "Gives 8 types of money drops randomly to the selected person",
    "Money Drop [ONLINE] 1",
    "Money Drop [ONLINE] 2",
    "(no delay) (fixed amount)",
    "This Gives RP and Money to other players",
    "Drop Random 5k $ 1K RP",
    "You can use this option infinitely",
    "Drop 75k and RP (Only works every 24 hours)",
    "(Only works every 24 hours)",
    "Drop 100k and RP",
    "Spawn Options",
    "Money Value",
    "Adjust the amount of money to drop",
    "Money Rain [LOCAL]",
    "ONLY WORKS FOR YOU",
    "Drop Everything",
    "Local Only",
    "Ammo Value",
    "Adjust the value to drop",
    "Enable Randomization",
    "If enabled, the generated ammo value will be 2000, 1900, 1616, 1500, 666, 500, 100.",
    "Value To 1000",
    "Enable this if you want the received ammo value to change to 1000",
    "Spawn Value",
    "Adjust the drop value.\nNote: The default value is 100%",
    "Random Delay",
    "If enabled, spawn time will be random.",
    "Health",
    "P's & Q's Snack",
    "Armor",
    "Parachute",
    "RP Loops",
    "Stop at Level",
    "Loop Delay",
    "Enable Loop",
    "Already at level",
    "Money[Casino Method]",
    "Make Money [CASINO]",
    "Shoot Money [Local]",
    "Shoot Money [ONLINE]",
    "Shoot Ammo",
    "Shoot Weapons",
    "Select which weapon to shoot",
    "only select one weapon",
    "Shoot Selected Weapon",
    "Remember to select a weapon first :)",
    "Shoot Health and Armor",
    "Shoot Misc",
    "Cleaned, Goodbye <3",
    "(Only works every 24 hours)",
    "[SafeMoneyLua]: Unexpected error. Please contact the provider. \n Error code: 236",
    "10-minute delay",
    "30-minute delay",
    "Random delay between 2 to 10 seconds",
    "180k Loop [Risky] [A]",
    "Enable random amount",
    "Works for options symbolized with '[A]'",
    "Adjust amount of money to receive",
    "Random delay loop",
    "Adjust loop delay",
     "Works for options symbolized with '[A]'\nExpressed in milliseconds",
     "Adjustable Amount \nMaximum amount ",
     "Money Settings",
      "Collect All [ONLY ONCE A DAY]",
       "Money List",
       "Select Money Type",
"Enable Car Money",
"Refresh Veh Table",
"Acid Lab Manager",
"Refill Supplies",
"Production Speed",
"15K Value Per Unit",
"Maximum Units 160",
"Hangar Manager Options",
"Max Price Per Crate [500K]",
"Remove Ron Cut",
"Remove Waiting Delay",
"Insta Sell",
"Air Delivery Only",
"Classic Heist [15M]",
"15M Heist Options",
"Extra Options",
"How To Use",
"1) First, unlock the heist you want to perform. \n2) Start the mission solo, skip the cutscene, and when you're at the planning board, select the option to complete the setup. \n3) Start the heist, invite your friends, and at the planning board, choose the preset you want. \n4) Once the heist has started, select the option to finish instantly.",
"Presets",
"Everyone Receives 15M",
"Only You Don’t Receive 15M",
"Remove Cooldown",
"Complete All Setups",
"It seems that you are currently not in any apartment.",
"The heist planning board couldn't be found in this apartment. Make sure you are in one of the high-end apartments.",
"Allow You Play Alone",
"Force Ready",
"Make all players forced ready at the planning board.",
"Unlock All Classic Heists",
"Misc Money Making",
"Option enabled, your current total money is $",
"\nNote: refunds will be applied only for purchases up to 15M\n~r~You must wait 20 minutes after each refund for it to work again.",
"Refund Purchase",
"Detects if you make a purchase and automatically refunds what you spent.\nNote: Only for purchases up to 15M",
"[SAFEMONEYLUA]\nA spending of $",
" was detected and successfully refunded to your wallet account ;)",
"Your purchase exceeds 15M, unfortunately, we will not be able to refund you :/",
"[SAFEMONEYLUA]\n~r~You need to wait ",
" ~r~more minutes for the next refund to work.",
"[SAFEMONEYLUA]\nA spending of $",
 " was detected \nAn attempt will be made to refund because ~r~you disabled the 20-minute wait time :/",
"[SAFEMONEYLUA]\nIt seems that didn't work :/",
"[SAFEMONEYLUA]\nYou have been refunded $",
" ~g~successfully :)",
"Ignore suggested time",
"Ignore the 20-minute time set in the script\nNote: This may lead to some purchases not being refunded correctly",




}

text_fr = {
    "DANGER: Toutes les fonctionnalités de ce script sont considérées comme risquées. Il existe une possibilité que votre compte soit suspendu dans un nombre de jours inconnu (les suspensions sont aléatoires). Vous avez été averti.",
    "En train de transférer de l'argent à la banque",
    "Veuillez envisager de désactiver la fonction pour éviter les interdictions",
    "Continuant avec la boucle",
    "Secondes écoulées :",
    "Argent Gagné : $",
    "Argent/Heure : $",
    "Argent/Minute : $",
    "Argent/Seconde : $",
    "Options de Sécurité",
    "Quelques options que je recommande que vous envisagiez d'activer ;)",
    "Options Pour Contrôler les Gains",
    "Outils Pour Tricher",
    "Assez utile pour les personnes qui veulent tricher avec leur compte",
    "Transactions limitées",
    "Ce sont des transactions qui ne peuvent être effectuées qu'une seule fois",
    "Activer la superposition",
    "Activer Tout Ci-Dessous",
    "Afficher le Temps Écoulé",
    "Afficher les Gains Totaux",
    "Afficher les Gains par Heure",
    "Afficher les Gains par Minute",
    "Afficher les Gains par Seconde",
    "Sélectionner une Couleur",
    "Sélectionnez une couleur pour le texte",
    "Options Rapides ;)",
    "Boucle De 1 Million [RECOMMANDÉE] [SÛRE]",
    "Vous donne 1 million chaque seconde jusqu'à ce que vous désactiviez cette fonction",
    "Transférer automatiquement votre argent",
    "Cela fonctionnera selon les valeurs assignées pour détecter et transférer",
    "Argent transféré avec succès :)",
    "Montant à Détecter",
    "Entrez la valeur que vous souhaitez détecter pour commencer à économiser automatiquement\nRemarque : la valeur initiale est la moitié de votre argent actuel",
    "Montant à Transférer",
    "Entrez la valeur que vous voulez enregistrer à la banque automatiquement\nRemarque : la valeur initiale sera l'argent que vous possédez actuellement",
    "Vous ne pouvez pas transférer un montant que vous ne possédez pas",
    "Cela prendra environ 30 secondes. :)", --fonction op100mxd
    "Commencer dans 3.",
    "Commencer dans 2.",
    "Commencer dans 1.",
    "Opération terminée. ;)",
    "Si l'opération n'a pas atteint les 'x' millions, utilisez la boucle de 1 million",
    "La fonction a déjà été exécutée. :/",
    "Triche [100 MILLIONS] [AUTOMATIQUE]",
    "Disponible une seule fois par compte (c'est recommandé) \nRemarque : Commencez d'abord par deux transactions de 15 millions, puis complétez-les avec des transactions de 1 million",
    "Exécution de bealone pour plus de sécurité ;)",
    "Transférer tout votre argent",
    "Transférer tout votre argent actuel à la banque",
    "Argent transféré avec succès :)",
    "Répéteur de Boucle",
    "Sélectionnez le nombre d'itérations pour la boucle de 1 million (maximum 500)",
    "Montant à Recevoir : ",
    "Boucle 1 MILLION [PAR ITÉRATIONS]",
    "Cela fonctionnera en fonction du nombre d'itérations que vous avez sélectionné ci-dessus",
    "Exécution de bealone pour plus de sécurité ;)",
    "Opération terminée. ;)\nMontant total reçu : ",
    "Éditeur de K/D",
    "Modifier le K/D.",
    "Boucle De 40 Millions [Lente] [PAS SÛRE]",
    "Détecté Actuellement (je pense)\nSi j'étais toi, je ne l'utiliserais pas",
    "Boucle de 5K [Jetons]",
    "Allez-vous vraiment utiliser cela ? :/",
    "Bloquer les Erreurs de Transaction",
    "Je vous recommande de l'activer pour éviter tout type d'erreur ;)",
    "Paramètres Optimisés",
    "Nous espérons que cela maximisera votre TPS et FPS :)",
    "Informations sur les Tricheries",
    "Vous avez des doutes sur la façon dont ça marche ?",
    "Combien d'argent puis-je gagner ?",
    "Au moins 100 millions toutes les 2 heures\nRemarque : Ne soyez pas trop cupide non plus.",
    "Puis-je entrer des milliards en toute sécurité ?",
    "Bien que ce ne soit pas recommandé, la réponse est oui, tout dépendra de la fréquence à laquelle vous entrez de l'argent",
    "Y a-t-il un risque d'interdiction ?",
    "Bien sûr que oui ! Tout dépendra du montant d'argent que vous avez décidé d'entrer\nRemarque : les suspensions sont aléatoires, généralement vous êtes banni pour 30 jours",
    "Quels sont les montants testés ?",
    "1 MILLION-50 MILLIONS [Sûr]\n50 MILLIONS-100 MILLIONS [Sûr]\n100M-1 MILLIARD [Sûr]\n1M-5 Milliards [Sûr]\n5B-7B [Peu sûr]\n7B+ [BANNISSABLE] [30 JOURS]",
    "KD Actuel", --ajouté à partir d'ici
    "Kills Actuels : ",
    "Affiche vos kills actuels.",
    "Morts Actuelles : ",
    "Affiche vos morts actuelles.",
    "Ratio Actuel : ",
    "Affiche votre ratio actuel.",
    "Nouveau K/D",
    "Nouvelle Valeur de Kills",
    "Sélectionnez une nouvelle valeur de kills.",
    "Nouvelle Valeur de Morts",
    "Sélectionnez une nouvelle valeur de morts.",
    "Nouveau Ratio : ",
    "Affiche votre nouveau K/D.",
    "Changer K/D",
    "Remplacez le K/D Actuel par le modifié.",
    "Votre K/D a changé à : ",
    "Kills Actuels : ",
    "Morts Actuelles : ",
    "Ratio Actuel : ",
    "Nouveau Ratio : ",
    "Vous devez être en ligne !",
    "~p~Chargé ~r~",
    " ~p~;)\n~p~Salut! ~o~",
    "\n~p~Nous trichons sur votre compte ~g~$$$ ~p~quoi ~p~? ;)",
    "Retrait d'Argent",--ajouté
    "Avez-vous dépassé les millions ? Voici la solution \nRemarque : Ajustez la valeur à retirer, jusqu'à 2 milliards de $!",
    "Montant à Retirer : ",
    "Une équipe balistique sera déployée, ne vous inquiétez pas",
    "Retirer Votre Argent",
    "Le montant d'argent ajusté ci-dessus sera retiré",
    "Opération terminée. ;)\nMontant total retiré : ",
    "Cette clé appartient à un autre utilisateur :/",
    "La clé est incorrecte. Réessayez.",
    "Entrer la Clé",
    "Entrez la clé pour débloquer le script",
    "Clé correcte ! Script débloqué.",
    "Options de Transfert d'Argent",
    "Options de Retrait d'Argent",
    "Options Supplémentaires",
    "500k en un Clic",
    "750k en un Clic",
    "Remarque : Utilisez une seule fois par jour.",
    "Triche [50 MILLIONS] [AUTOMATIQUE]",
    "Triche [30 MILLIONS] [AUTOMATIQUE]",
    "Triche [15 MILLIONS] [AUTOMATIQUE]",
    "Veuillez sélectionner un montant valide",
    "Boucle de 50k",
    "Vous donne 50k par seconde",
    "Boucle de 10 Millions",
    "Vous donne 10 millions par seconde",
    "10 Millions En Un Clic",
    "Vous donne 10 millions en un clic (Il est recommandé de ne pas en abuser, sinon cela ne fonctionnera pas)",
    "20 Millions En Un Clic",
    "Vous donne 20 millions en un clic (Il est recommandé de ne pas en abuser, sinon cela ne fonctionnera pas)",
    "Supprimer Tout Votre Argent",
    "Vous laisse avec 1$",
    "Options en un clic ;)",
    "aller à la liste des joueurs", --ultimate_drop
    "Messages",
    "Méthode Roulette",
    ">> Si vous voulez gagner de l'argent, venez au casino, jouez à la roulette et misez le maximum sur la première douzaine (50k) et sur le Rouge 1 (5k), gagnez 3, perdez 1, 550k par minute.",
    ">> Si vous voulez gagner de l'argent, venez au casino, jouez au blackjack. Cliquez sur la mise maximale, puis choisissez 'tenir' et gagnez le double de votre mise.",
    "Méthode Roulette Désactivée",
    "Notifie que la méthode a été désactivée",
    ">> La méthode pour gagner de l'argent au casino a été désactivée :)",
    "Nouvelle Implémentation",
    "Options de Chutes Ultime",
    "Liste des Chutes",
    "Chutes Ultime",
    "Options de Spawn [Général]",
    "Drop d'Argent",
    "Drop d'Argent [LOCAL]",
    "Drop d'Argent [ONLINE]",
    "Drop d'Armes",
    "Drop de Munitions",
    "Drop de Santé et Armure",
    "Drop Divers",
    "Options de Spawn",
    "Options de Superposition",
    "Argent Total Donné: $",
    "Afficher l'Argent Donné",
    "Activer ou désactiver l'info d'argent total donné",
    "Munitions Totales Données: ",
    "Afficher les Munitions Données",
    "Activer ou désactiver l'info de munitions totales données",
    "Armes Totales Données: ",
    "Afficher les Armes Données",
    "Activer ou désactiver l'info d'armes totales données",
    "Santé et Armure Totales Données: ",
    "Afficher Santé et Armure Données",
    "Activer ou désactiver l'info de santé et armure totales données",
    "Divers Totales Donnés: ",
    "Afficher Divers Donnés",
    "Activer ou désactiver l'info de divers totaux donnés",
    "Réinitialiser Toutes les Valeurs",
    "Réinitialiser tous les totaux donnés à '0'",
    "Délai de Spawn",
    "Ajuster le temps d'attente pour le drop.\nNote: Cela n'affectera pas l'option 'Pluie d'Argent'",
    "Ajuster Valeur 'X'",
    "Ajuster la position de drop\nNote: Cela n'affectera pas l'option 'Pluie d'Argent'",
    "Ajuster Valeur 'Y'",
    "Ajuster Valeur 'Z'",
    "Ajuster la hauteur de drop\nNote: Cela n'affectera pas l'option 'Pluie d'Argent'\nSi défini sur '0', la valeur sera de 1.5",
    "Donner de l'Argent à ",
    "Pluie d'Argent [ONLINE]",
    "Drop d'Argent [Aléatoire]",
    "Donne 8 types de drops d'argent de manière aléatoire à la personne sélectionnée",
    "Drop d'Argent [ONLINE] 1",
    "Drop d'Argent [ONLINE] 2",
    "(sans délai) (montant fixe)",
    "Cela donne RP et de l'argent aux autres joueurs",
    "Drop Aléatoire 5k $ 1K RP",
    "Vous pouvez utiliser cette option indéfiniment",
    "Drop 75k et RP (Ne fonctionne qu'une fois toutes les 24 heures)",
    "(Ne fonctionne qu'une fois toutes les 24 heures)",
    "Drop 100k et RP",
    "Options de Spawn",
    "Valeur de l'Argent",
    "Ajuster le montant d'argent à dropper",
    "Pluie d'Argent [LOCAL]",
    "NE FONCTIONNE QUE POUR VOUS",
    "Tout Dropper",
    "Seulement Local",
    "Valeur des Munitions",
    "Ajuster la valeur à dropper",
    "Activer la Randomisation",
    "Si activé, la valeur de munitions générée sera 2000, 1900, 1616, 1500, 666, 500, 100.",
    "Valeur à 1000",
    "Activer ceci si vous voulez que la valeur de munitions reçue passe à 1000",
    "Valeur de Spawn",
    "Ajuster la valeur de drop.\nNote: La valeur par défaut est de 100%",
    "Délai Aléatoire",
    "Si activé, le temps de spawn sera aléatoire.",
    "Santé",
    "Snack P's & Q's",
    "Armure",
    "Parachute",
    "Boucles RP",
    "Arrêter au Niveau",
    "Délai de la Boucle",
    "Activer la Boucle",
    "Déjà au niveau",
    "Argent[Méthode Casino]",
    "Gagner de l'Argent [CASINO]",
    "Tirer de l'Argent [Local]",
    "Tirer de l'Argent [ONLINE]",
    "Tirer des Munitions",
    "Tirer des Armes",
    "Sélectionnez quelle arme tirer",
    "sélectionnez seulement une arme",
    "Tirer Arme Sélectionnée",
    "N'oubliez pas de sélectionner une arme d'abord :)",
    "Tirer Santé et Armure",
    "Tirer Divers",
    "Nettoyé, Au revoir <3",
    "(Fonctionne seulement toutes les 24 heures)",
    "[SafeMoneyLua]: Erreur inattendue. Veuillez contacter le fournisseur. \n Code d'erreur : 236",
    "Délai de 10 minutes",
    "Délai de 30 minutes",
    "Délai aléatoire entre 2 à 10 secondes",
    "Boucle de 180k [Risky] [A]",
    "Activer la quantité aléatoire",
    "Fonctionne pour les options symbolisées par '[A]'",
    "Ajuster la quantité d'argent à recevoir",
    "Boucle de délai aléatoire",
    "Ajuster le délai de la boucle",
     "Fonctionne pour les options symbolisées par '[A]'\nExprimé en millisecondes",
     "Montant ajustable \nMontant maximum ",
     "Paramètres d'Argent",
     "Encaisser Tout [UNE SEULE FOIS PAR JOUR]",
     "Liste d'Argent",
     "Sélectionner le type d'argent",
"Activer l'argent des véhicules",
"Actualiser la table des véhicules",
"Laboratoire d'Acide",
"Recharger les Fournitures",
"Vitesse de Production [X10]",
"15K Valeur Par Unité",
"Maximum d'Unités 160",
"Options du Responsable du Hangar",
"Prix Maximum Par Caisson [500K]",
"Supprimer la Part de Ron",
"Supprimer le Délai d'Attente",
"Vente Instantanée",
"Livraison Aérienne Uniquement",
"Classic Heist [15M]",
"Options de Heist 15M",
"Options Supplémentaires",
"Comment Utiliser",
"1) Tout d'abord, débloquez le casse que vous souhaitez réaliser. \n2) Lancez la mission en solo, passez la cinématique et lorsque vous êtes au tableau de planification, sélectionnez l'option pour compléter la préparation. \n3) Lancez le casse, invitez vos amis et au tableau de planification, choisissez le preset que vous souhaitez. \n4) Une fois le casse lancé, sélectionnez l'option pour finir instantanément.",
"Presets",
"Tout le Monde Reçoit 15M",
"Seulement Vous Ne Recevez Pas 15M",
"Retirer le Cooldown",
"Compléter Tous les Paramètres",
"Il semble que vous ne soyez actuellement dans aucun appartement.",
"Le tableau de planification du casse n'a pas pu être trouvé dans cet appartement. Assurez-vous d'être dans un des appartements haut de gamme.",
"Permettre de Jouer Seul",
"Forcer Prêt",
"Faire en sorte que tous les joueurs soient prêts de force au tableau de planification.",
"Débloquer Tous les Casses Classiques",
"Argent Divers",
"Option activée, votre argent total actuel est de $",
"\nRemarque : les remboursements ne seront appliqués que pour les achats allant jusqu'à 15 millions\n~r~Vous devez attendre 20 minutes après chaque remboursement pour qu'il fonctionne à nouveau.",
"Remboursement d'achat",
"Détecte si vous effectuez un achat et rembourse automatiquement ce que vous avez dépensé.\nRemarque : uniquement pour les achats allant jusqu'à 15 millions",
"[SAFEMONEYLUA]\nUne dépense de $",
" a été détectée et remboursée avec succès sur votre compte portefeuille ;)",
"Votre achat dépasse 15 millions, malheureusement, nous ne pourrons pas vous rembourser :/",
"[SAFEMONEYLUA]\n~r~Vous devez attendre ",
" ~r~plus de minutes pour que le prochain remboursement fonctionne.",
"[SAFEMONEYLUA]\nUne dépense de $",
 "  a été détectée\nUne tentative de remboursement sera faite car ~r~vous avez désactivé le temps d'attente de 20 minutes :/",
"[SAFEMONEYLUA]\nIl semblerait que cela n'ait pas fonctionné :/",
"[SAFEMONEYLUA]\nVous avez été remboursé de $",
" ~g~avec succès :)",
"Ignorer le temps suggéré",
"Ignores le temps de 20 minutes défini dans le script\nRemarque : Cela peut entraîner le fait que certains achats ne soient pas correctement remboursés",


}


dicionary = {
    pt = {
      WARNING_ALERT = text_pt[1],
      transferdinalban = text_pt[2],
      CONSIDER_DEACTIVATE = text_pt[3],
      CONTINUING_LOOP = text_pt[4],
      SECONDS_ELAPSED = text_pt[5],
      EARNED_MONEY = text_pt[6],
      MONEY_PER_HOUR = text_pt[7],
      MONEY_PER_MINUTE = text_pt[8],
      MONEY_PER_SECOND = text_pt[9],
      SECURITY_OPTIONS = text_pt[10],
      opcionesreac = text_pt[11],
      LOOP_OPTIONS = text_pt[12],
      CHEAT_TOOLS = text_pt[13],
      Util_Option = text_pt[14],
      LIMITED_TRANSACTIONS = text_pt[15],
      sontransaccionesque = text_pt[16],
      ENABLE_OVERLAY = text_pt[17],
      ENABLE_ALL_BELOW = text_pt[18],
      SHOW_ELAPSED_TIME = text_pt[19],
      SHOW_TOTAL_EARNINGS = text_pt[20],
      SHOW_EARNINGS_PER_HOUR = text_pt[21],
      SHOW_EARNINGS_PER_MINUTE = text_pt[22],
      SHOW_EARNINGS_PER_SECOND = text_pt[23],
      SELECT_COLOR = text_pt[24],
      selectcolorfortext = text_pt[25],  -- Corregido aquí
      QUICK_OPTIONS = text_pt[26],  -- Corregido aquí
      LOOP_1M_RECOMMENDED = text_pt[27],
      LOOP_1M_DESCRIPTION = text_pt[28],
      AUTO_TRANSFER_MONEY = text_pt[29],
      AUTO_TRANSFER_DESCRIPTION = text_pt[30],
      MONEY_TRANSFER_SUCCESS = text_pt[31],
      DETECT_AMOUNT = text_pt[32],
      Detectamountdescription = text_pt[33],
      TRANSFER_AMOUNT = text_pt[34],  -- Corregido aquí
      transferamountdecript = text_pt[35],
      CANNOT_TRANSFER_AMOUNT = text_pt[36],
      TRANSFER_DELAY_MESSAGE = text_pt[37],
      COUNTDOWN_3 = text_pt[38],
      COUNTDOWN_2 = text_pt[39],
      COUNTDOWN_1 = text_pt[40],
      OPERATION_COMPLETED = text_pt[41],
      OPERATION_NOT_100M = text_pt[42],
      OPERATION_ALREADY_EXECUTED = text_pt[43],
      CHEAT_100M_AUTO = text_pt[44],
      CHEAT_100M_DESCRIPTION = text_pt[45],
      RUNNING_BEALONE = text_pt[46],
      TRANSFER_ALL_MONEY = text_pt[47],
      transfer_allmoneydescript = text_pt[48],
      TRANSFER_ALL_SUCCESS = text_pt[49],
      repetidorLOOP_ITERATIONS = text_pt[50],
      repetidordescription = text_pt[51],
      AMOUNT_TO_RECEIVE = text_pt[52],
      LOOP_BY_ITERATIONS = text_pt[53],
      loopbyinterationsdescript = text_pt[54],
      RUNNING_BEALONE_LOOP = text_pt[55],
      OPERATION_COMPLETED_TOTAL_RECEIVED = text_pt[56],
      KD_EDITOR = text_pt[57],
      EDIT_KD = text_pt[58],
      LOOP_40M_SLOW = text_pt[59],
      CURRENTLY_DETECTED = text_pt[60],
      LOOP_5K_CHIPS = text_pt[61],
      REALLY_USE_THIS = text_pt[62],
      BLOCK_TRANSACTION_ERRORS = text_pt[63],
      transactionerrordescript = text_pt[64],
      OPTIMIZED_SETTINGS = text_pt[65],
      optimizedsettingdescript = text_pt[66],
      CHEAT_INFORMATION = text_pt[67],
      dudas_ABOUT_HOW_IT_GOES = text_pt[68],
      HOW_MUCH_MONEY_CAN_I_MAKE = text_pt[69],
      answerdescription1 = text_pt[70],
      CAN_I_SAFELY_ENTER_BILLIONS = text_pt[71],
      answerdescription2 = text_pt[72],
      RISK_OF_BAN = text_pt[73],
      answerdescription3 = text_pt[74],
      TESTED_AMOUNTS = text_pt[75],
      answerdescription4 = text_pt[76],
      kdactual = text_pt[77],-- nuevo añadido
      kills_actuales = text_pt[78],
      SHOW_ACTUALLY_KILLS = text_pt[79],
      ACTUALLY_DE = text_pt[80],
      SHOW_ACTUALLY_DEAD = text_pt[81],
      ACTUAL_RATIO = text_pt[82],
      SHOW_CURRENT_RATIO = text_pt[83],
      NEW_KD = text_pt[84],
      NEW_KILLS_VALUE = text_pt[85],
      SELECT_NEW_KILLS_VALUE = text_pt[86],
      NEW_DEATHS_VALUE = text_pt[87],
      SELECT_NEW_DEATHS_VALUE = text_pt[88],
      NEW_RATIO_LABEL = text_pt[89],
      SHOW_NEW_KD = text_pt[90],
      CHANGE_KD = text_pt[91],
      REPLACE_CURRENT_KD = text_pt[92],
      KD_CHANGED_TO = text_pt[93],
      CURRENT_KILLS = text_pt[94],
      CURRENT_DEATHS = text_pt[95],
      CURRENT_RATIO = text_pt[96],
      NEW_RATIO = text_pt[97],
      NEED_TO_BE_ONLINE = text_pt[98],
      LOADED_MESSAGE = text_pt[99],
      W_MESSAGE1 = text_pt[100],  -- Últimas tres traducciones
      W_MESSAGE2 = text_pt[101],
      REMOVEDOR_DINERO = text_pt[102],--nuevo
      REMOVER_DESCRIPT = text_pt[103],
      AMOUNT_TO_REMOVE = text_pt[104],
      DEPLOY_BALLISTIC = text_pt[105],
      REMOVER_DINERO = text_pt[106],
      REMOVER_DESCRIPCION2 = text_pt[107],
      TOTAL_REMOVED_AMOUNT = text_pt[108],
      UNKNOW_SYSTEM = text_pt[109],
      UNKNOW_SYSTEM2 = text_pt[110],
      UNKNOW_SYSTEM3 = text_pt[111],
      UNKNOW_SYSTEM4 = text_pt[112],
      UNKNOW_SYSTEM5 = text_pt[113],
      TRANSFER_OPTIONS = text_pt[114],
      REMOVE_OPTIONS = text_pt[115],
      EXTRA_OPTIONS = text_pt[116],
      ONE_CLICK_OPT = text_pt[117],
      ONE_CLICK_OPT2 = text_pt[118],
      ONE_CLICK_INFO = text_pt[119],
      CHEAT_50M_AUTO = text_pt[120],
      CHEAT_30M_AUTO = text_pt[121],
      CHEAT_15M_AUTO = text_pt[122],
      IS_AMOUNT_VALID = text_pt[123],
      LOOP_10M_OPTION = text_pt[124],
      LOOP_10M_DESC = text_pt[125],
      LOOP_100M_OPTION = text_pt[126],
      LOOP_100M_DESC = text_pt[127],
      ONE_CLICK_OPT_3 = text_pt[128],
      ONE_CLICK_DESC_3 = text_pt[129],
      ONE_CLICK_OPT_4 = text_pt[130],
      ONE_CLICK_DESC_4 = text_pt[131],
      DELETE_ALL_MONEY = text_pt[132],
      DELETE_ALL_MONEY_DESC = text_pt[133],
      ONE_CLICK_MENU = text_pt[134],
      GO_TO_PLAYER_LIST = text_pt[135], -- ultimate drop
MESSAGES = text_pt[136],
ROULETTE_METHOD = text_pt[137],
MAKE_MONEY_ROULETTE = text_pt[138],
MAKE_MONEY_BLACKJACK = text_pt[139],
ROULETTE_METHOD_DISABLED = text_pt[140],
NOTIFIES_METHOD_DISABLED = text_pt[141],
METHOD_DISABLED_MESSAGE = text_pt[142],
NEW_IMPLEMENTATION = text_pt[143],
ULTIMATE_DROPS_OPTIONS = text_pt[144],
DROPS_LIST = text_pt[145],
ULTIMATE_DROPS = text_pt[146],
SPAWN_OPTIONS_GENERAL = text_pt[147],
MONEY_DROP = text_pt[148],
MONEY_DROP_LOCAL = text_pt[149],
MONEY_DROP_ONLINE = text_pt[150],
WEAPON_DROP = text_pt[151],
AMMO_DROP = text_pt[152],
HEALTH_ARMOR_DROP = text_pt[153],
MISC_DROP = text_pt[154],
SPAWN_OPTIONS = text_pt[155],
OVERLAY_OPTIONS = text_pt[156],
TOTAL_MONEY_DONATED = text_pt[157],
SHOW_DONATED_MONEY = text_pt[158],
ENABLE_DISABLE_DONATED_MONEY = text_pt[159],
TOTAL_AMMO_DONATED = text_pt[160],
SHOW_DONATED_AMMO = text_pt[161],
ENABLE_DISABLE_DONATED_AMMO = text_pt[162],
TOTAL_WEAPONS_DONATED = text_pt[163],
SHOW_DONATED_WEAPONS = text_pt[164],
ENABLE_DISABLE_DONATED_WEAPONS = text_pt[165],
TOTAL_HEALTH_ARMOR_DONATED = text_pt[166],
SHOW_DONATED_HEALTH_ARMOR = text_pt[167],
ENABLE_DISABLE_DONATED_HEALTH_ARMOR = text_pt[168],
TOTAL_MISC_DONATED = text_pt[169],
SHOW_DONATED_MISC = text_pt[170],
ENABLE_DISABLE_DONATED_MISC = text_pt[171],
RESET_ALL_VALUES = text_pt[172],
RESET_DONATED_TOTALS = text_pt[173],
SPAWN_DELAY = text_pt[174],
ADJUST_DROP_WAIT_TIME = text_pt[175],
ADJUST_X_VALUE = text_pt[176],
ADJUST_DROP_POSITION = text_pt[177],
ADJUST_Y_VALUE = text_pt[178],
ADJUST_Z_VALUE = text_pt[179],
ADJUST_DROP_HEIGHT = text_pt[180],
GIVING_MONEY_TO = text_pt[181],
MONEY_RAIN_ONLINE = text_pt[182],
MONEY_DROP_RANDOM = text_pt[183],
GIVES_RANDOM_MONEY_DROP = text_pt[184],
MONEY_DROP_ONLINE_1 = text_pt[185],
MONEY_DROP_ONLINE_2 = text_pt[186],
NO_DELAY_FIXED_AMOUNT = text_pt[187],
RP_MONEY_OTHER_PLAYERS = text_pt[188],
DROP_RANDOM_5K_1K_RP = text_pt[189],
USE_OPTION_INFINITELY = text_pt[190],
DROP_75K_RP_EVERY_24HRS = text_pt[191],
ONLY_WORKS_EVERY_24HRS = text_pt[192],
DROP_100K_RP = text_pt[193],
SPAWN_OPTIONS_2 = text_pt[194],
MONEY_VALUE = text_pt[195],
ADJUST_MONEY_DROP_AMOUNT = text_pt[196],
MONEY_RAIN_LOCAL = text_pt[197],
ONLY_WORKS_FOR_YOU = text_pt[198],
DROP_EVERYTHING = text_pt[199],
LOCAL_ONLY = text_pt[200],
AMMO_VALUE = text_pt[201],
ADJUST_AMMO_VALUE_DROP = text_pt[202],
ENABLE_RANDOMIZATION = text_pt[203],
GENERATED_AMMO_VALUES = text_pt[204],
VALUE_TO_1000 = text_pt[205],
CHANGE_RECEIVED_AMMO_VALUE = text_pt[206],
SPAWN_VALUE = text_pt[207],
ADJUST_DROP_VALUE = text_pt[208],
RANDOM_DELAY = text_pt[209],
ENABLE_RANDOM_SPAWN_TIME = text_pt[210],
HEALTH = text_pt[211],
PS_QS_SNACK = text_pt[212],
ARMOR = text_pt[213],
PARACHUTE = text_pt[214],
RP_LOOPS = text_pt[215],
STOP_AT_LEVEL = text_pt[216],
LOOP_DELAY = text_pt[217],
ENABLE_LOOP = text_pt[218],
ALREADY_AT_LEVEL = text_pt[219],
MONEY_CASINO_METHOD = text_pt[220],
MAKE_MONEY_CASINO = text_pt[221],
SHOOT_MONEY_LOCAL = text_pt[222],
SHOOT_MONEY_ONLINE = text_pt[223],
SHOOT_AMMO = text_pt[224],
SHOOT_WEAPONS = text_pt[225],
SELECT_WEAPON_TO_SHOOT = text_pt[226],
ONLY_SELECT_ONE_WEAPON = text_pt[227],
SHOOT_SELECTED_WEAPON = text_pt[228],
REMEMBER_SELECT_WEAPON_FIRST = text_pt[229],
SHOOT_HEALTH_ARMOR = text_pt[230],
SHOOT_MISC = text_pt[231],
CLEANED_GOODBYE = text_pt[232],
WORKS_EVERY_24HS = text_pt[233],
TRANSLATION_FUNCTION = text_pt[234],
DELAY10_TEXT_INFO = text_pt[235],
DELAY30_TEXT_INFO = text_pt[236],
RANDOM_DELAY_INFO = text_pt[237],
RANDOM_LOOP_100K = text_pt[238],
ENABLE_RANDOM_AMOUNT = text_pt[239],
WORKS_FOR_A = text_pt[240],
ADJUST_MONEY_AMOUNT = text_pt[241],
ENABLE_RANDOM_DELAY_LOOP = text_pt[242],
ADJUST_DELAY_LOOP = text_pt[243],
WORKS_FOR_A_MS = text_pt[244],
MAX_AMOUNT_ADJUSTABLE = text_pt[245],
MONEY_SETTINGS = text_pt[246],
COLLECT_ALL = text_pt[247],
LIST_OF_MONEY = text_pt[248],
SELECT_MONEY_TYPE = text_pt[249],
ENABLE_CAR_MONEY_OPT = text_pt[250],
REFRESH_VEH_TABLE_OPT = text_pt[251],
ACID_LAB_OPT = text_pt[252],
REFILL_ALOPT = text_pt[253],
INCREMENT_S_PDT = text_pt[254],
VALUE_AC_OPT = text_pt[255],
MAX_AC_U_D = text_pt[256],
H_M_OPT = text_pt[257],
MAX_PR_PC = text_pt[258],
REMOVE_CUTT = text_pt[259],
REMOVE_W_D = text_pt[260],
INSTASELLOPT = text_pt[261],
ONLY_DEL_AIR_DESC = text_pt[262],

CLASSIC_HEIST_TITLE = text_pt[263],
HEIST_OPTION = text_pt[264],
EXTRA_OPTIONS = text_pt[265],
HOW_TO_USE = text_pt[266],
STEP_TO_FOLLOW = text_pt[267],
PRESETS = text_pt[268],
ALL_RECEIVE_15M = text_pt[269],
ONLY_YOU_DONT_RECEIVE_15M = text_pt[270],
REMOVE_COOLDOWN = text_pt[271],
COMPLETE_ALL_SETUPS = text_pt[272],
NO_APARTMENT = text_pt[273],
NO_PLANNING_BOARD = text_pt[274],
ALLOW_PLAY_ALONE = text_pt[275],
FORCE_READY = text_pt[276],
FORCE_READY_DESC = text_pt[277],
UNLOCK_ALL_CLASSIC_HEISTS = text_pt[278],
MISC_MONEY_MAKING = text_pt[279],

OPTION_ENABLED_RP = text_pt[280],
OPTION_ENABLED_2_RP = text_pt[281],
DEVOLVER_COMPRA_TITLE = text_pt[282],
DEVOLVER_COMPRA_DESC = text_pt[283],
SE_DETECTO_INFO = text_pt[284],
SE_DETECTO_2_INFO = text_pt[285],
AMMOUNT_OVERRIDE_ERROR = text_pt[286],
INFO_ALERT_TIME = text_pt[287],
INFO_ALERT_2_TIME = text_pt[288],
INFO_AMMOUNT_SPEND_DETECTED = text_pt[289],
INFO_AMMOUNT_SPEND2_DETECTED  = text_pt[290],
SEEMS_MESSAGE = text_pt[291],
REFUND_SUCCESS = text_pt[292],
REFUND2_SUCCESS = text_pt[293],
IGNORE_SUGGESTED_TIME = text_pt[294],
IGNORE_SUGGESTED_TIME_DESC = text_pt[295]


    },

    es = {
      WARNING_ALERT = text_es[1],
      transferdinalban = text_es[2],
      CONSIDER_DEACTIVATE = text_es[3],
      CONTINUING_LOOP = text_es[4],
      SECONDS_ELAPSED = text_es[5],
      EARNED_MONEY = text_es[6],
      MONEY_PER_HOUR = text_es[7],
      MONEY_PER_MINUTE = text_es[8],
      MONEY_PER_SECOND = text_es[9],
      SECURITY_OPTIONS = text_es[10],
      opcionesreac = text_es[11],
      LOOP_OPTIONS = text_es[12],
      CHEAT_TOOLS = text_es[13],
      Util_Option = text_es[14],
      LIMITED_TRANSACTIONS = text_es[15],
      sontransaccionesque = text_es[16],
      ENABLE_OVERLAY = text_es[17],
      ENABLE_ALL_BELOW = text_es[18],
      SHOW_ELAPSED_TIME = text_es[19],
      SHOW_TOTAL_EARNINGS = text_es[20],
      SHOW_EARNINGS_PER_HOUR = text_es[21],
      SHOW_EARNINGS_PER_MINUTE = text_es[22],
      SHOW_EARNINGS_PER_SECOND = text_es[23],
      SELECT_COLOR = text_es[24],
      selectcolorfortext = text_es[25],  -- Corregido aquí
      QUICK_OPTIONS = text_es[26],  -- Corregido aquí
      LOOP_1M_RECOMMENDED = text_es[27],
      LOOP_1M_DESCRIPTION = text_es[28],
      AUTO_TRANSFER_MONEY = text_es[29],
      AUTO_TRANSFER_DESCRIPTION = text_es[30],
      MONEY_TRANSFER_SUCCESS = text_es[31],
      DETECT_AMOUNT = text_es[32],
      Detectamountdescription = text_es[33],
      TRANSFER_AMOUNT = text_es[34],  -- Corregido aquí
      transferamountdecript = text_es[35],
      CANNOT_TRANSFER_AMOUNT = text_es[36],
      TRANSFER_DELAY_MESSAGE = text_es[37],
      COUNTDOWN_3 = text_es[38],
      COUNTDOWN_2 = text_es[39],
      COUNTDOWN_1 = text_es[40],
      OPERATION_COMPLETED = text_es[41],
      OPERATION_NOT_100M = text_es[42],
      OPERATION_ALREADY_EXECUTED = text_es[43],
      CHEAT_100M_AUTO = text_es[44],
      CHEAT_100M_DESCRIPTION = text_es[45],
      RUNNING_BEALONE = text_es[46],
      TRANSFER_ALL_MONEY = text_es[47],
      transfer_allmoneydescript = text_es[48],
      TRANSFER_ALL_SUCCESS = text_es[49],
      repetidorLOOP_ITERATIONS = text_es[50],
      repetidordescription = text_es[51],
      AMOUNT_TO_RECEIVE = text_es[52],
      LOOP_BY_ITERATIONS = text_es[53],
      loopbyinterationsdescript = text_es[54],
      RUNNING_BEALONE_LOOP = text_es[55],
      OPERATION_COMPLETED_TOTAL_RECEIVED = text_es[56],
      KD_EDITOR = text_es[57],
      EDIT_KD = text_es[58],
      LOOP_40M_SLOW = text_es[59],
      CURRENTLY_DETECTED = text_es[60],
      LOOP_5K_CHIPS = text_es[61],
      REALLY_USE_THIS = text_es[62],
      BLOCK_TRANSACTION_ERRORS = text_es[63],
      transactionerrordescript = text_es[64],
      OPTIMIZED_SETTINGS = text_es[65],
      optimizedsettingdescript = text_es[66],
      CHEAT_INFORMATION = text_es[67],
      dudas_ABOUT_HOW_IT_GOES = text_es[68],
      HOW_MUCH_MONEY_CAN_I_MAKE = text_es[69],
      answerdescription1 = text_es[70],
      CAN_I_SAFELY_ENTER_BILLIONS = text_es[71],
      answerdescription2 = text_es[72],
      RISK_OF_BAN = text_es[73],
      answerdescription3 = text_es[74],
      TESTED_AMOUNTS = text_es[75],
      answerdescription4 = text_es[76],
      kdactual = text_es[77],-- nuevo añadido
      kills_actuales = text_es[78],
      SHOW_ACTUALLY_KILLS = text_es[79],
      ACTUALLY_DE = text_es[80],
      SHOW_ACTUALLY_DEAD = text_es[81],
      ACTUAL_RATIO = text_es[82],
      SHOW_CURRENT_RATIO = text_es[83],
      NEW_KD = text_es[84],
      NEW_KILLS_VALUE = text_es[85],
      SELECT_NEW_KILLS_VALUE = text_es[86],
      NEW_DEATHS_VALUE = text_es[87],
      SELECT_NEW_DEATHS_VALUE = text_es[88],
      NEW_RATIO_LABEL = text_es[89],
      SHOW_NEW_KD = text_es[90],
      CHANGE_KD = text_es[91],
      REPLACE_CURRENT_KD = text_es[92],
      KD_CHANGED_TO = text_es[93],
      CURRENT_KILLS = text_es[94],
      CURRENT_DEATHS = text_es[95],
      CURRENT_RATIO = text_es[96],
      NEW_RATIO = text_es[97],
      NEED_TO_BE_ONLINE = text_es[98],
      LOADED_MESSAGE = text_es[99],
      W_MESSAGE1 = text_es[100],  -- Últimas tres traducciones
      W_MESSAGE2 = text_es[101],
      REMOVEDOR_DINERO = text_es[102],--nuevo
      REMOVER_DESCRIPT = text_es[103],
      AMOUNT_TO_REMOVE = text_es[104],
      DEPLOY_BALLISTIC = text_es[105],
      REMOVER_DINERO = text_es[106],
      REMOVER_DESCRIPCION2 = text_es[107],
      TOTAL_REMOVED_AMOUNT = text_es[108],
      UNKNOW_SYSTEM = text_es[109],
      UNKNOW_SYSTEM2 = text_es[110],
      UNKNOW_SYSTEM3 = text_es[111],
      UNKNOW_SYSTEM4 = text_es[112],
      UNKNOW_SYSTEM5 = text_es[113],
      TRANSFER_OPTIONS = text_es[114],
      REMOVE_OPTIONS = text_es[115],
      EXTRA_OPTIONS = text_es[116],
      ONE_CLICK_OPT = text_es[117],
      ONE_CLICK_OPT2 = text_es[118],
      ONE_CLICK_INFO = text_es[119],
      CHEAT_50M_AUTO = text_es[120],
      CHEAT_30M_AUTO = text_es[121],
      CHEAT_15M_AUTO = text_es[122],
      IS_AMOUNT_VALID = text_es[123],
      LOOP_10M_OPTION = text_es[124],
      LOOP_10M_DESC = text_es[125],
      LOOP_100M_OPTION = text_es[126],
      LOOP_100M_DESC = text_es[127],
      ONE_CLICK_OPT_3 = text_es[128],
      ONE_CLICK_DESC_3 = text_es[129],
      ONE_CLICK_OPT_4 = text_es[130],
      ONE_CLICK_DESC_4 = text_es[131],
      DELETE_ALL_MONEY = text_es[132],
      DELETE_ALL_MONEY_DESC = text_es[133],
      ONE_CLICK_MENU = text_es[134],
      GO_TO_PLAYER_LIST = text_es[135], 
MESSAGES = text_es[136], --ultimate_drop
ROULETTE_METHOD = text_es[137],
MAKE_MONEY_ROULETTE = text_es[138],
MAKE_MONEY_BLACKJACK = text_es[139],
ROULETTE_METHOD_DISABLED = text_es[140],
NOTIFIES_METHOD_DISABLED = text_es[141],
METHOD_DISABLED_MESSAGE = text_es[142],
NEW_IMPLEMENTATION = text_es[143],
ULTIMATE_DROPS_OPTIONS = text_es[144],
DROPS_LIST = text_es[145],
ULTIMATE_DROPS = text_es[146],
SPAWN_OPTIONS_GENERAL = text_es[147],
MONEY_DROP = text_es[148],
MONEY_DROP_LOCAL = text_es[149],
MONEY_DROP_ONLINE = text_es[150],
WEAPON_DROP = text_es[151],
AMMO_DROP = text_es[152],
HEALTH_ARMOR_DROP = text_es[153],
MISC_DROP = text_es[154],
SPAWN_OPTIONS = text_es[155],
OVERLAY_OPTIONS = text_es[156],
TOTAL_MONEY_DONATED = text_es[157],
SHOW_DONATED_MONEY = text_es[158],
ENABLE_DISABLE_DONATED_MONEY = text_es[159],
TOTAL_AMMO_DONATED = text_es[160],
SHOW_DONATED_AMMO = text_es[161],
ENABLE_DISABLE_DONATED_AMMO = text_es[162],
TOTAL_WEAPONS_DONATED = text_es[163],
SHOW_DONATED_WEAPONS = text_es[164],
ENABLE_DISABLE_DONATED_WEAPONS = text_es[165],
TOTAL_HEALTH_ARMOR_DONATED = text_es[166],
SHOW_DONATED_HEALTH_ARMOR = text_es[167],
ENABLE_DISABLE_DONATED_HEALTH_ARMOR = text_es[168],
TOTAL_MISC_DONATED = text_es[169],
SHOW_DONATED_MISC = text_es[170],
ENABLE_DISABLE_DONATED_MISC = text_es[171],
RESET_ALL_VALUES = text_es[172],
RESET_DONATED_TOTALS = text_es[173],
SPAWN_DELAY = text_es[174],
ADJUST_DROP_WAIT_TIME = text_es[175],
ADJUST_X_VALUE = text_es[176],
ADJUST_DROP_POSITION = text_es[177],
ADJUST_Y_VALUE = text_es[178],
ADJUST_Z_VALUE = text_es[179],
ADJUST_DROP_HEIGHT = text_es[180],
GIVING_MONEY_TO = text_es[181],
MONEY_RAIN_ONLINE = text_es[182],
MONEY_DROP_RANDOM = text_es[183],
GIVES_RANDOM_MONEY_DROP = text_es[184],
MONEY_DROP_ONLINE_1 = text_es[185],
MONEY_DROP_ONLINE_2 = text_es[186],
NO_DELAY_FIXED_AMOUNT = text_es[187],
RP_MONEY_OTHER_PLAYERS = text_es[188],
DROP_RANDOM_5K_1K_RP = text_es[189],
USE_OPTION_INFINITELY = text_es[190],
DROP_75K_RP_EVERY_24HRS = text_es[191],
ONLY_WORKS_EVERY_24HRS = text_es[192],
DROP_100K_RP = text_es[193],
SPAWN_OPTIONS_2 = text_es[194],
MONEY_VALUE = text_es[195],
ADJUST_MONEY_DROP_AMOUNT = text_es[196],
MONEY_RAIN_LOCAL = text_es[197],
ONLY_WORKS_FOR_YOU = text_es[198],
DROP_EVERYTHING = text_es[199],
LOCAL_ONLY = text_es[200],
AMMO_VALUE = text_es[201],
ADJUST_AMMO_VALUE_DROP = text_es[202],
ENABLE_RANDOMIZATION = text_es[203],
GENERATED_AMMO_VALUES = text_es[204],
VALUE_TO_1000 = text_es[205],
CHANGE_RECEIVED_AMMO_VALUE = text_es[206],
SPAWN_VALUE = text_es[207],
ADJUST_DROP_VALUE = text_es[208],
RANDOM_DELAY = text_es[209],
ENABLE_RANDOM_SPAWN_TIME = text_es[210],
HEALTH = text_es[211],
PS_QS_SNACK = text_es[212],
ARMOR = text_es[213],
PARACHUTE = text_es[214],
RP_LOOPS = text_es[215],
STOP_AT_LEVEL = text_es[216],
LOOP_DELAY = text_es[217],
ENABLE_LOOP = text_es[218],
ALREADY_AT_LEVEL = text_es[219],
MONEY_CASINO_METHOD = text_es[220],
MAKE_MONEY_CASINO = text_es[221],
SHOOT_MONEY_LOCAL = text_es[222],
SHOOT_MONEY_ONLINE = text_es[223],
SHOOT_AMMO = text_es[224],
SHOOT_WEAPONS = text_es[225],
SELECT_WEAPON_TO_SHOOT = text_es[226],
ONLY_SELECT_ONE_WEAPON = text_es[227],
SHOOT_SELECTED_WEAPON = text_es[228],
REMEMBER_SELECT_WEAPON_FIRST = text_es[229],
SHOOT_HEALTH_ARMOR = text_es[230],
SHOOT_MISC = text_es[231],
CLEANED_GOODBYE = text_es[232],
WORKS_EVERY_24HS = text_es[233],
TRANSLATION_FUNCTION = text_es[234],
DELAY10_TEXT_INFO = text_es[235],
DELAY30_TEXT_INFO = text_es[236],
RANDOM_DELAY_INFO = text_es[237],
RANDOM_LOOP_100K = text_es[238],
ENABLE_RANDOM_AMOUNT = text_es[239],
WORKS_FOR_A = text_es[240],
ADJUST_MONEY_AMOUNT = text_es[241],
ENABLE_RANDOM_DELAY_LOOP = text_es[242],
ADJUST_DELAY_LOOP = text_es[243],
WORKS_FOR_A_MS = text_es[244],
MAX_AMOUNT_ADJUSTABLE = text_es[245],
MONEY_SETTINGS = text_es[246],
COLLECT_ALL = text_es[247],
LIST_OF_MONEY = text_es[248],
SELECT_MONEY_TYPE = text_es[249],
ENABLE_CAR_MONEY_OPT = text_es[250],
REFRESH_VEH_TABLE_OPT = text_es[251],
ACID_LAB_OPT = text_es[252],
REFILL_ALOPT = text_es[253],
INCREMENT_S_PDT = text_es[254],
VALUE_AC_OPT = text_es[255],
MAX_AC_U_D = text_es[256],
H_M_OPT = text_es[257],
MAX_PR_PC = text_es[258],
REMOVE_CUTT = text_es[259],
REMOVE_W_D = text_es[260],
INSTASELLOPT = text_es[261],
ONLY_DEL_AIR_DESC = text_es[262],

CLASSIC_HEIST_TITLE = text_es[263],
HEIST_OPTION = text_es[264],
EXTRA_OPTIONS = text_es[265],
HOW_TO_USE = text_es[266],
STEP_TO_FOLLOW = text_es[267],
PRESETS = text_es[268],
ALL_RECEIVE_15M = text_es[269],
ONLY_YOU_DONT_RECEIVE_15M = text_es[270],
REMOVE_COOLDOWN = text_es[271],
COMPLETE_ALL_SETUPS = text_es[272],
NO_APARTMENT = text_es[273],
NO_PLANNING_BOARD = text_es[274],
ALLOW_PLAY_ALONE = text_es[275],
FORCE_READY = text_es[276],
FORCE_READY_DESC = text_es[277],
UNLOCK_ALL_CLASSIC_HEISTS = text_es[278],
MISC_MONEY_MAKING = text_es[279],

OPTION_ENABLED_RP = text_es[280],
OPTION_ENABLED_2_RP = text_es[281],
DEVOLVER_COMPRA_TITLE = text_es[282],
DEVOLVER_COMPRA_DESC = text_es[283],
SE_DETECTO_INFO = text_es[284],
SE_DETECTO_2_INFO = text_es[285],
AMMOUNT_OVERRIDE_ERROR = text_es[286],
INFO_ALERT_TIME = text_es[287],
INFO_ALERT_2_TIME = text_es[288],

INFO_AMMOUNT_SPEND_DETECTED = text_es[289],
INFO_AMMOUNT_SPEND2_DETECTED  = text_es[290],
SEEMS_MESSAGE = text_es[291],
REFUND_SUCCESS = text_es[292],
REFUND2_SUCCESS = text_es[293],
IGNORE_SUGGESTED_TIME = text_es[294],
IGNORE_SUGGESTED_TIME_DESC = text_es[295]

      },



    en = {
      WARNING_ALERT = text_en[1],
      transferdinalban = text_en[2],
      CONSIDER_DEACTIVATE = text_en[3],
      CONTINUING_LOOP = text_en[4],
      SECONDS_ELAPSED = text_en[5],
      EARNED_MONEY = text_en[6],
      MONEY_PER_HOUR = text_en[7],
      MONEY_PER_MINUTE = text_en[8],
      MONEY_PER_SECOND = text_en[9],
      SECURITY_OPTIONS = text_en[10],
      opcionesreac = text_en[11],
      LOOP_OPTIONS = text_en[12],
      CHEAT_TOOLS = text_en[13],
      Util_Option = text_en[14],
      LIMITED_TRANSACTIONS = text_en[15],
      sontransaccionesque = text_en[16],
      ENABLE_OVERLAY = text_en[17],
      ENABLE_ALL_BELOW = text_en[18],
      SHOW_ELAPSED_TIME = text_en[19],
      SHOW_TOTAL_EARNINGS = text_en[20],
      SHOW_EARNINGS_PER_HOUR = text_en[21],
      SHOW_EARNINGS_PER_MINUTE = text_en[22],
      SHOW_EARNINGS_PER_SECOND = text_en[23],
      SELECT_COLOR = text_en[24],
      selectcolorfortext = text_en[25],  -- Corregido aquí
      QUICK_OPTIONS = text_en[26],  -- Corregido aquí
      LOOP_1M_RECOMMENDED = text_en[27],
      LOOP_1M_DESCRIPTION = text_en[28],
      AUTO_TRANSFER_MONEY = text_en[29],
      AUTO_TRANSFER_DESCRIPTION = text_en[30],
      MONEY_TRANSFER_SUCCESS = text_en[31],
      DETECT_AMOUNT = text_en[32],
      Detectamountdescription = text_en[33],
      TRANSFER_AMOUNT = text_en[34],  -- Corregido aquí
      transferamountdecript = text_en[35],
      CANNOT_TRANSFER_AMOUNT = text_en[36],
      TRANSFER_DELAY_MESSAGE = text_en[37],
      COUNTDOWN_3 = text_en[38],
      COUNTDOWN_2 = text_en[39],
      COUNTDOWN_1 = text_en[40],
      OPERATION_COMPLETED = text_en[41],
      OPERATION_NOT_100M = text_en[42],
      OPERATION_ALREADY_EXECUTED = text_en[43],
      CHEAT_100M_AUTO = text_en[44],
      CHEAT_100M_DESCRIPTION = text_en[45],
      RUNNING_BEALONE = text_en[46],
      TRANSFER_ALL_MONEY = text_en[47],
      transfer_allmoneydescript = text_en[48],
      TRANSFER_ALL_SUCCESS = text_en[49],
      repetidorLOOP_ITERATIONS = text_en[50],
      repetidordescription = text_en[51],
      AMOUNT_TO_RECEIVE = text_en[52],
      LOOP_BY_ITERATIONS = text_en[53],
      loopbyinterationsdescript = text_en[54],
      RUNNING_BEALONE_LOOP = text_en[55],
      OPERATION_COMPLETED_TOTAL_RECEIVED = text_en[56],
      KD_EDITOR = text_en[57],
      EDIT_KD = text_en[58],
      LOOP_40M_SLOW = text_en[59],
      CURRENTLY_DETECTED = text_en[60],
      LOOP_5K_CHIPS = text_en[61],
      REALLY_USE_THIS = text_en[62],
      BLOCK_TRANSACTION_ERRORS = text_en[63],
      transactionerrordescript = text_en[64],
      OPTIMIZED_SETTINGS = text_en[65],
      optimizedsettingdescript = text_en[66],
      CHEAT_INFORMATION = text_en[67],
      dudas_ABOUT_HOW_IT_GOES = text_en[68],
      HOW_MUCH_MONEY_CAN_I_MAKE = text_en[69],
      answerdescription1 = text_en[70],
      CAN_I_SAFELY_ENTER_BILLIONS = text_en[71],
      answerdescription2 = text_en[72],
      RISK_OF_BAN = text_en[73],
      answerdescription3 = text_en[74],
      TESTED_AMOUNTS = text_en[75],
      answerdescription4 = text_en[76],
      kdactual = text_en[77],-- nuevo añadido
      kills_actuales = text_en[78],
      SHOW_ACTUALLY_KILLS = text_en[79],
      ACTUALLY_DE = text_en[80],
      SHOW_ACTUALLY_DEAD = text_en[81],
      ACTUAL_RATIO = text_en[82],
      SHOW_CURRENT_RATIO = text_en[83],
      NEW_KD = text_en[84],
      NEW_KILLS_VALUE = text_en[85],
      SELECT_NEW_KILLS_VALUE = text_en[86],
      NEW_DEATHS_VALUE = text_en[87],
      SELECT_NEW_DEATHS_VALUE = text_en[88],
      NEW_RATIO_LABEL = text_en[89],
      SHOW_NEW_KD = text_en[90],
      CHANGE_KD = text_en[91],
      REPLACE_CURRENT_KD = text_en[92],
      KD_CHANGED_TO = text_en[93],
      CURRENT_KILLS = text_en[94],
      CURRENT_DEATHS = text_en[95],
      CURRENT_RATIO = text_en[96],
      NEW_RATIO = text_en[97],
      NEED_TO_BE_ONLINE = text_en[98],
      LOADED_MESSAGE = text_en[99],
      W_MESSAGE1 = text_en[100],  -- Últimas tres traducciones
      W_MESSAGE2 = text_en[101],
      REMOVEDOR_DINERO = text_en[102],--nuevo
      REMOVER_DESCRIPT = text_en[103],
      AMOUNT_TO_REMOVE = text_en[104],
      DEPLOY_BALLISTIC = text_en[105],
      REMOVER_DINERO = text_en[106],
      REMOVER_DESCRIPCION2 = text_en[107],
      TOTAL_REMOVED_AMOUNT = text_en[108],
      UNKNOW_SYSTEM = text_en[109],
      UNKNOW_SYSTEM2 = text_en[110],
      UNKNOW_SYSTEM3 = text_en[111],
      UNKNOW_SYSTEM4 = text_en[112],
      UNKNOW_SYSTEM5 = text_en[113],
      TRANSFER_OPTIONS = text_en[114],
      REMOVE_OPTIONS = text_en[115],
      EXTRA_OPTIONS = text_en[116],
      ONE_CLICK_OPT = text_en[117],
      ONE_CLICK_OPT2 = text_en[118],
      ONE_CLICK_INFO = text_en[119],
      CHEAT_50M_AUTO = text_en[120],
      CHEAT_30M_AUTO = text_en[121],
      CHEAT_15M_AUTO = text_en[122],
      IS_AMOUNT_VALID = text_en[123],
      LOOP_10M_OPTION = text_en[124],
      LOOP_10M_DESC = text_en[125],
      LOOP_100M_OPTION = text_en[126],
      LOOP_100M_DESC = text_en[127],
      ONE_CLICK_OPT_3 = text_en[128],
      ONE_CLICK_DESC_3 = text_en[129],
      ONE_CLICK_OPT_4 = text_en[130],
      ONE_CLICK_DESC_4 = text_en[131],
      DELETE_ALL_MONEY = text_en[132],
      DELETE_ALL_MONEY_DESC = text_en[133],
      ONE_CLICK_MENU = text_en[134],
      GO_TO_PLAYER_LIST = text_en[135], -- ultimate drop
MESSAGES = text_en[136],
ROULETTE_METHOD = text_en[137],
MAKE_MONEY_ROULETTE = text_en[138],
MAKE_MONEY_BLACKJACK = text_en[139],
ROULETTE_METHOD_DISABLED = text_en[140],
NOTIFIES_METHOD_DISABLED = text_en[141],
METHOD_DISABLED_MESSAGE = text_en[142],
NEW_IMPLEMENTATION = text_en[143],
ULTIMATE_DROPS_OPTIONS = text_en[144],
DROPS_LIST = text_en[145],
ULTIMATE_DROPS = text_en[146],
SPAWN_OPTIONS_GENERAL = text_en[147],
MONEY_DROP = text_en[148],
MONEY_DROP_LOCAL = text_en[149],
MONEY_DROP_ONLINE = text_en[150],
WEAPON_DROP = text_en[151],
AMMO_DROP = text_en[152],
HEALTH_ARMOR_DROP = text_en[153],
MISC_DROP = text_en[154],
SPAWN_OPTIONS = text_en[155],
OVERLAY_OPTIONS = text_en[156],
TOTAL_MONEY_DONATED = text_en[157],
SHOW_DONATED_MONEY = text_en[158],
ENABLE_DISABLE_DONATED_MONEY = text_en[159],
TOTAL_AMMO_DONATED = text_en[160],
SHOW_DONATED_AMMO = text_en[161],
ENABLE_DISABLE_DONATED_AMMO = text_en[162],
TOTAL_WEAPONS_DONATED = text_en[163],
SHOW_DONATED_WEAPONS = text_en[164],
ENABLE_DISABLE_DONATED_WEAPONS = text_en[165],
TOTAL_HEALTH_ARMOR_DONATED = text_en[166],
SHOW_DONATED_HEALTH_ARMOR = text_en[167],
ENABLE_DISABLE_DONATED_HEALTH_ARMOR = text_en[168],
TOTAL_MISC_DONATED = text_en[169],
SHOW_DONATED_MISC = text_en[170],
ENABLE_DISABLE_DONATED_MISC = text_en[171],
RESET_ALL_VALUES = text_en[172],
RESET_DONATED_TOTALS = text_en[173],
SPAWN_DELAY = text_en[174],
ADJUST_DROP_WAIT_TIME = text_en[175],
ADJUST_X_VALUE = text_en[176],
ADJUST_DROP_POSITION = text_en[177],
ADJUST_Y_VALUE = text_en[178],
ADJUST_Z_VALUE = text_en[179],
ADJUST_DROP_HEIGHT = text_en[180],
GIVING_MONEY_TO = text_en[181],
MONEY_RAIN_ONLINE = text_en[182],
MONEY_DROP_RANDOM = text_en[183],
GIVES_RANDOM_MONEY_DROP = text_en[184],
MONEY_DROP_ONLINE_1 = text_en[185],
MONEY_DROP_ONLINE_2 = text_en[186],
NO_DELAY_FIXED_AMOUNT = text_en[187],
RP_MONEY_OTHER_PLAYERS = text_en[188],
DROP_RANDOM_5K_1K_RP = text_en[189],
USE_OPTION_INFINITELY = text_en[190],
DROP_75K_RP_EVERY_24HRS = text_en[191],
ONLY_WORKS_EVERY_24HRS = text_en[192],
DROP_100K_RP = text_en[193],
SPAWN_OPTIONS_2 = text_en[194],
MONEY_VALUE = text_en[195],
ADJUST_MONEY_DROP_AMOUNT = text_en[196],
MONEY_RAIN_LOCAL = text_en[197],
ONLY_WORKS_FOR_YOU = text_en[198],
DROP_EVERYTHING = text_en[199],
LOCAL_ONLY = text_en[200],
AMMO_VALUE = text_en[201],
ADJUST_AMMO_VALUE_DROP = text_en[202],
ENABLE_RANDOMIZATION = text_en[203],
GENERATED_AMMO_VALUES = text_en[204],
VALUE_TO_1000 = text_en[205],
CHANGE_RECEIVED_AMMO_VALUE = text_en[206],
SPAWN_VALUE = text_en[207],
ADJUST_DROP_VALUE = text_en[208],
RANDOM_DELAY = text_en[209],
ENABLE_RANDOM_SPAWN_TIME = text_en[210],
HEALTH = text_en[211],
PS_QS_SNACK = text_en[212],
ARMOR = text_en[213],
PARACHUTE = text_en[214],
RP_LOOPS = text_en[215],
STOP_AT_LEVEL = text_en[216],
LOOP_DELAY = text_en[217],
ENABLE_LOOP = text_en[218],
ALREADY_AT_LEVEL = text_en[219],
MONEY_CASINO_METHOD = text_en[220],
MAKE_MONEY_CASINO = text_en[221],
SHOOT_MONEY_LOCAL = text_en[222],
SHOOT_MONEY_ONLINE = text_en[223],
SHOOT_AMMO = text_en[224],
SHOOT_WEAPONS = text_en[225],
SELECT_WEAPON_TO_SHOOT = text_en[226],
ONLY_SELECT_ONE_WEAPON = text_en[227],
SHOOT_SELECTED_WEAPON = text_en[228],
REMEMBER_SELECT_WEAPON_FIRST = text_en[229],
SHOOT_HEALTH_ARMOR = text_en[230],
SHOOT_MISC = text_en[231],
CLEANED_GOODBYE = text_en[232],
WORKS_EVERY_24HS = text_en[233],
TRANSLATION_FUNCTION = text_en[234],
DELAY10_TEXT_INFO = text_en[235],
DELAY30_TEXT_INFO = text_en[236],
RANDOM_DELAY_INFO = text_en[237],
RANDOM_LOOP_100K = text_en[238],
ENABLE_RANDOM_AMOUNT = text_en[239],
WORKS_FOR_A = text_en[240],
ADJUST_MONEY_AMOUNT = text_en[241],
ENABLE_RANDOM_DELAY_LOOP = text_en[242],
ADJUST_DELAY_LOOP = text_en[243],
WORKS_FOR_A_MS = text_en[244],
MAX_AMOUNT_ADJUSTABLE = text_en[245],
MONEY_SETTINGS = text_en[246],
COLLECT_ALL = text_en[247],
LIST_OF_MONEY = text_en[248],
SELECT_MONEY_TYPE = text_en[249],
ENABLE_CAR_MONEY_OPT = text_en[250],
REFRESH_VEH_TABLE_OPT = text_en[251],
ACID_LAB_OPT = text_en[252],
REFILL_ALOPT = text_en[253],
INCREMENT_S_PDT = text_en[254],
VALUE_AC_OPT = text_en[255],
MAX_AC_U_D = text_en[256],
H_M_OPT = text_en[257],
MAX_PR_PC = text_en[258],
REMOVE_CUTT = text_en[259],
REMOVE_W_D = text_en[260],
INSTASELLOPT = text_en[261],
ONLY_DEL_AIR_DESC = text_en[262],
CLASSIC_HEIST_TITLE = text_en[263],

HEIST_OPTION = text_en[264],
EXTRA_OPTIONS = text_en[265],
HOW_TO_USE = text_en[266],
STEP_TO_FOLLOW = text_en[267],
PRESETS = text_en[268],
ALL_RECEIVE_15M = text_en[269],
ONLY_YOU_DONT_RECEIVE_15M = text_en[270],
REMOVE_COOLDOWN = text_en[271],
COMPLETE_ALL_SETUPS = text_en[272],
NO_APARTMENT = text_en[273],
NO_PLANNING_BOARD = text_en[274],
ALLOW_PLAY_ALONE = text_en[275],
FORCE_READY = text_en[276],
FORCE_READY_DESC = text_en[277],
UNLOCK_ALL_CLASSIC_HEISTS = text_en[278],
MISC_MONEY_MAKING = text_en[279],
OPTION_ENABLED_RP = text_en[280],
OPTION_ENABLED_2_RP = text_en[281],
DEVOLVER_COMPRA_TITLE = text_en[282],
DEVOLVER_COMPRA_DESC = text_en[283],
SE_DETECTO_INFO = text_en[284],
SE_DETECTO_2_INFO = text_en[285],
AMMOUNT_OVERRIDE_ERROR = text_en[286],
INFO_ALERT_TIME = text_en[287],
INFO_ALERT_2_TIME = text_en[288],

INFO_AMMOUNT_SPEND_DETECTED = text_en[289],
INFO_AMMOUNT_SPEND2_DETECTED  = text_en[290],
SEEMS_MESSAGE = text_en[291],
REFUND_SUCCESS = text_en[292],
REFUND2_SUCCESS = text_en[293],
IGNORE_SUGGESTED_TIME = text_en[294],
IGNORE_SUGGESTED_TIME_DESC = text_en[295]

    },

    fr = {
      WARNING_ALERT = text_fr[1],
      transferdinalban = text_fr[2],
      CONSIDER_DEACTIVATE = text_fr[3],
      CONTINUING_LOOP = text_fr[4],
      SECONDS_ELAPSED = text_fr[5],
      EARNED_MONEY = text_fr[6],
      MONEY_PER_HOUR = text_fr[7],
      MONEY_PER_MINUTE = text_fr[8],
      MONEY_PER_SECOND = text_fr[9],
      SECURITY_OPTIONS = text_fr[10],
      opcionesreac = text_fr[11],
      LOOP_OPTIONS = text_fr[12],
      CHEAT_TOOLS = text_fr[13],
      Util_Option = text_fr[14],
      LIMITED_TRANSACTIONS = text_fr[15],
      sontransaccionesque = text_fr[16],
      ENABLE_OVERLAY = text_fr[17],
      ENABLE_ALL_BELOW = text_fr[18],
      SHOW_ELAPSED_TIME = text_fr[19],
      SHOW_TOTAL_EARNINGS = text_fr[20],
      SHOW_EARNINGS_PER_HOUR = text_fr[21],
      SHOW_EARNINGS_PER_MINUTE = text_fr[22],
      SHOW_EARNINGS_PER_SECOND = text_fr[23],
      SELECT_COLOR = text_fr[24],
      selectcolorfortext = text_fr[25],  -- Corregido aquí
      QUICK_OPTIONS = text_fr[26],  -- Corregido aquí
      LOOP_1M_RECOMMENDED = text_fr[27],
      LOOP_1M_DESCRIPTION = text_fr[28],
      AUTO_TRANSFER_MONEY = text_fr[29],
      AUTO_TRANSFER_DESCRIPTION = text_fr[30],
      MONEY_TRANSFER_SUCCESS = text_fr[31],
      DETECT_AMOUNT = text_fr[32],
      Detectamountdescription = text_fr[33],
      TRANSFER_AMOUNT = text_fr[34],  -- Corregido aquí
      transferamountdecript = text_fr[35],
      CANNOT_TRANSFER_AMOUNT = text_fr[36],
      TRANSFER_DELAY_MESSAGE = text_fr[37],
      COUNTDOWN_3 = text_fr[38],
      COUNTDOWN_2 = text_fr[39],
      COUNTDOWN_1 = text_fr[40],
      OPERATION_COMPLETED = text_fr[41],
      OPERATION_NOT_100M = text_fr[42],
      OPERATION_ALREADY_EXECUTED = text_fr[43],
      CHEAT_100M_AUTO = text_fr[44],
      CHEAT_100M_DESCRIPTION = text_fr[45],
      RUNNING_BEALONE = text_fr[46],
      TRANSFER_ALL_MONEY = text_fr[47],
      transfer_allmoneydescript = text_fr[48],
      TRANSFER_ALL_SUCCESS = text_fr[49],
      repetidorLOOP_ITERATIONS = text_fr[50],
      repetidordescription = text_fr[51],
      AMOUNT_TO_RECEIVE = text_fr[52],
      LOOP_BY_ITERATIONS = text_fr[53],
      loopbyinterationsdescript = text_fr[54],
      RUNNING_BEALONE_LOOP = text_fr[55],
      OPERATION_COMPLETED_TOTAL_RECEIVED = text_fr[56],
      KD_EDITOR = text_fr[57],
      EDIT_KD = text_fr[58],
      LOOP_40M_SLOW = text_fr[59],
      CURRENTLY_DETECTED = text_fr[60],
      LOOP_5K_CHIPS = text_fr[61],
      REALLY_USE_THIS = text_fr[62],
      BLOCK_TRANSACTION_ERRORS = text_fr[63],
      transactionerrordescript = text_fr[64],
      OPTIMIZED_SETTINGS = text_fr[65],
      optimizedsettingdescript = text_fr[66],
      CHEAT_INFORMATION = text_fr[67],
      dudas_ABOUT_HOW_IT_GOES = text_fr[68],
      HOW_MUCH_MONEY_CAN_I_MAKE = text_fr[69],
      answerdescription1 = text_fr[70],
      CAN_I_SAFELY_ENTER_BILLIONS = text_fr[71],
      answerdescription2 = text_fr[72],
      RISK_OF_BAN = text_fr[73],
      answerdescription3 = text_fr[74],
      TESTED_AMOUNTS = text_fr[75],
      answerdescription4 = text_fr[76],
      kdactual = text_fr[77],-- nuevo añadido
      kills_actuales = text_fr[78],
      SHOW_ACTUALLY_KILLS = text_fr[79],
      ACTUALLY_DE = text_fr[80],
      SHOW_ACTUALLY_DEAD = text_fr[81],
      ACTUAL_RATIO = text_fr[82],
      SHOW_CURRENT_RATIO = text_fr[83],
      NEW_KD = text_fr[84],
      NEW_KILLS_VALUE = text_fr[85],
      SELECT_NEW_KILLS_VALUE = text_fr[86],
      NEW_DEATHS_VALUE = text_fr[87],
      SELECT_NEW_DEATHS_VALUE = text_fr[88],
      NEW_RATIO_LABEL = text_fr[89],
      SHOW_NEW_KD = text_fr[90],
      CHANGE_KD = text_fr[91],
      REPLACE_CURRENT_KD = text_fr[92],
      KD_CHANGED_TO = text_fr[93],
      CURRENT_KILLS = text_fr[94],
      CURRENT_DEATHS = text_fr[95],
      CURRENT_RATIO = text_fr[96],
      NEW_RATIO = text_fr[97],
      NEED_TO_BE_ONLINE = text_fr[98],
      LOADED_MESSAGE = text_fr[99],
      W_MESSAGE1 = text_fr[100],  -- Últimas tres traducciones
      W_MESSAGE2 = text_fr[101],
      REMOVEDOR_DINERO = text_fr[102],--nuevo
      REMOVER_DESCRIPT = text_fr[103],
      AMOUNT_TO_REMOVE = text_fr[104],
      DEPLOY_BALLISTIC = text_fr[105],
      REMOVER_DINERO = text_fr[106],
      REMOVER_DESCRIPCION2 = text_fr[107],
      TOTAL_REMOVED_AMOUNT = text_fr[108],
      UNKNOW_SYSTEM = text_fr[109],
      UNKNOW_SYSTEM2 = text_fr[110],
      UNKNOW_SYSTEM3 = text_fr[111],
      UNKNOW_SYSTEM4 = text_fr[112],
      UNKNOW_SYSTEM5 = text_fr[113],
      TRANSFER_OPTIONS = text_fr[114],
      REMOVE_OPTIONS = text_fr[115],
      EXTRA_OPTIONS = text_fr[116],
      ONE_CLICK_OPT = text_fr[117],
      ONE_CLICK_OPT2 = text_fr[118],
      ONE_CLICK_INFO = text_fr[119],
      CHEAT_50M_AUTO = text_fr[120],
      CHEAT_30M_AUTO = text_fr[121],
      CHEAT_15M_AUTO = text_fr[122],
      IS_AMOUNT_VALID = text_fr[123],
      LOOP_10M_OPTION = text_fr[124],
      LOOP_10M_DESC = text_fr[125],
      LOOP_100M_OPTION = text_fr[126],
      LOOP_100M_DESC = text_fr[127],
      ONE_CLICK_OPT_3 = text_fr[128],
      ONE_CLICK_DESC_3 = text_fr[129],
      ONE_CLICK_OPT_4 = text_fr[130],
      ONE_CLICK_DESC_4 = text_fr[131],
      DELETE_ALL_MONEY = text_fr[132],
      DELETE_ALL_MONEY_DESC = text_fr[133],
      ONE_CLICK_MENU = text_fr[134],
      GO_TO_PLAYER_LIST = text_fr[135], -- ultimate drop
MESSAGES = text_fr[136], 
ROULETTE_METHOD = text_fr[137],
MAKE_MONEY_ROULETTE = text_fr[138],
MAKE_MONEY_BLACKJACK = text_fr[139],
ROULETTE_METHOD_DISABLED = text_fr[140],
NOTIFIES_METHOD_DISABLED = text_fr[141],
METHOD_DISABLED_MESSAGE = text_fr[142],
NEW_IMPLEMENTATION = text_fr[143],
ULTIMATE_DROPS_OPTIONS = text_fr[144],
DROPS_LIST = text_fr[145],
ULTIMATE_DROPS = text_fr[146],
SPAWN_OPTIONS_GENERAL = text_fr[147],
MONEY_DROP = text_fr[148],
MONEY_DROP_LOCAL = text_fr[149],
MONEY_DROP_ONLINE = text_fr[150],
WEAPON_DROP = text_fr[151],
AMMO_DROP = text_fr[152],
HEALTH_ARMOR_DROP = text_fr[153],
MISC_DROP = text_fr[154],
SPAWN_OPTIONS = text_fr[155],
OVERLAY_OPTIONS = text_fr[156],
TOTAL_MONEY_DONATED = text_fr[157],
SHOW_DONATED_MONEY = text_fr[158],
ENABLE_DISABLE_DONATED_MONEY = text_fr[159],
TOTAL_AMMO_DONATED = text_fr[160],
SHOW_DONATED_AMMO = text_fr[161],
ENABLE_DISABLE_DONATED_AMMO = text_fr[162],
TOTAL_WEAPONS_DONATED = text_fr[163],
SHOW_DONATED_WEAPONS = text_fr[164],
ENABLE_DISABLE_DONATED_WEAPONS = text_fr[165],
TOTAL_HEALTH_ARMOR_DONATED = text_fr[166],
SHOW_DONATED_HEALTH_ARMOR = text_fr[167],
ENABLE_DISABLE_DONATED_HEALTH_ARMOR = text_fr[168],
TOTAL_MISC_DONATED = text_fr[169],
SHOW_DONATED_MISC = text_fr[170],
ENABLE_DISABLE_DONATED_MISC = text_fr[171],--
RESET_ALL_VALUES = text_fr[172],
RESET_DONATED_TOTALS = text_fr[173],
SPAWN_DELAY = text_fr[174],
ADJUST_DROP_WAIT_TIME = text_fr[175],
ADJUST_X_VALUE = text_fr[176],
ADJUST_DROP_POSITION = text_fr[177],
ADJUST_Y_VALUE = text_fr[178],
ADJUST_Z_VALUE = text_fr[179],
ADJUST_DROP_HEIGHT = text_fr[180],
GIVING_MONEY_TO = text_fr[181],
MONEY_RAIN_ONLINE = text_fr[182],
MONEY_DROP_RANDOM = text_fr[183],
GIVES_RANDOM_MONEY_DROP = text_fr[184],
MONEY_DROP_ONLINE_1 = text_fr[185],
MONEY_DROP_ONLINE_2 = text_fr[186],
NO_DELAY_FIXED_AMOUNT = text_fr[187],
RP_MONEY_OTHER_PLAYERS = text_fr[188],
DROP_RANDOM_5K_1K_RP = text_fr[189],
USE_OPTION_INFINITELY = text_fr[190],
DROP_75K_RP_EVERY_24HRS = text_fr[191],
ONLY_WORKS_EVERY_24HRS = text_fr[192],
DROP_100K_RP = text_fr[193],
SPAWN_OPTIONS_2 = text_fr[194],
MONEY_VALUE = text_fr[195],
ADJUST_MONEY_DROP_AMOUNT = text_fr[196],
MONEY_RAIN_LOCAL = text_fr[197],
ONLY_WORKS_FOR_YOU = text_fr[198],
DROP_EVERYTHING = text_fr[199],
LOCAL_ONLY = text_fr[200],
AMMO_VALUE = text_fr[201],
ADJUST_AMMO_VALUE_DROP = text_fr[202],
ENABLE_RANDOMIZATION = text_fr[203],
GENERATED_AMMO_VALUES = text_fr[204],
VALUE_TO_1000 = text_fr[205],
CHANGE_RECEIVED_AMMO_VALUE = text_fr[206],
SPAWN_VALUE = text_fr[207],
ADJUST_DROP_VALUE = text_fr[208],
RANDOM_DELAY = text_fr[209],
ENABLE_RANDOM_SPAWN_TIME = text_fr[210],
HEALTH = text_fr[211],
PS_QS_SNACK = text_fr[212],
ARMOR = text_fr[213],
PARACHUTE = text_fr[214],
RP_LOOPS = text_fr[215],
STOP_AT_LEVEL = text_fr[216],
LOOP_DELAY = text_fr[217],
ENABLE_LOOP = text_fr[218],
ALREADY_AT_LEVEL = text_fr[219],
MONEY_CASINO_METHOD = text_fr[220],
MAKE_MONEY_CASINO = text_fr[221],
SHOOT_MONEY_LOCAL = text_fr[222],
SHOOT_MONEY_ONLINE = text_fr[223],
SHOOT_AMMO = text_fr[224],
SHOOT_WEAPONS = text_fr[225],
SELECT_WEAPON_TO_SHOOT = text_fr[226],
ONLY_SELECT_ONE_WEAPON = text_fr[227],
SHOOT_SELECTED_WEAPON = text_fr[228],
REMEMBER_SELECT_WEAPON_FIRST = text_fr[229],
SHOOT_HEALTH_ARMOR = text_fr[230],
SHOOT_MISC = text_fr[231],
CLEANED_GOODBYE = text_fr[232],
WORKS_EVERY_24HS = text_fr[233],
TRANSLATION_FUNCTION = text_fr[234],
DELAY10_TEXT_INFO = text_fr[235],
DELAY30_TEXT_INFO = text_fr[236],
RANDOM_DELAY_INFO = text_fr[237],
RANDOM_LOOP_100K = text_fr[238],
ENABLE_RANDOM_AMOUNT = text_fr[239],
WORKS_FOR_A = text_fr[240],
ADJUST_MONEY_AMOUNT = text_fr[241],
ENABLE_RANDOM_DELAY_LOOP = text_fr[242],
ADJUST_DELAY_LOOP = text_fr[243],
WORKS_FOR_A_MS = text_fr[244],
MAX_AMOUNT_ADJUSTABLE = text_fr[245],
MONEY_SETTINGS = text_fr[246],
COLLECT_ALL = text_fr[247],
LIST_OF_MONEY = text_fr[248],
SELECT_MONEY_TYPE = text_fr[249],
ENABLE_CAR_MONEY_OPT = text_fr[250],
REFRESH_VEH_TABLE_OPT = text_fr[251],
ACID_LAB_OPT = text_fr[252],
REFILL_ALOPT = text_fr[253],
INCREMENT_S_PDT = text_fr[254],
VALUE_AC_OPT = text_fr[255],
MAX_AC_U_D = text_fr[256],
H_M_OPT = text_fr[257],
MAX_PR_PC = text_fr[258],
REMOVE_CUTT = text_fr[259],
REMOVE_W_D = text_fr[260],
INSTASELLOPT = text_fr[261],
ONLY_DEL_AIR_DESC = text_fr[262],

CLASSIC_HEIST_TITLE = text_fr[263],
HEIST_OPTION = text_fr[264],
EXTRA_OPTIONS = text_fr[265],
HOW_TO_USE = text_fr[266],
STEP_TO_FOLLOW = text_fr[267],
PRESETS = text_fr[268],
ALL_RECEIVE_15M = text_fr[269],
ONLY_YOU_DONT_RECEIVE_15M = text_fr[270],
REMOVE_COOLDOWN = text_fr[271],
COMPLETE_ALL_SETUPS = text_fr[272],
NO_APARTMENT = text_fr[273],
NO_PLANNING_BOARD = text_fr[274],
ALLOW_PLAY_ALONE = text_fr[275],
FORCE_READY = text_fr[276],
FORCE_READY_DESC = text_fr[277],
UNLOCK_ALL_CLASSIC_HEISTS = text_fr[278],
MISC_MONEY_MAKING = text_fr[279],

OPTION_ENABLED_RP = text_fr[280],
OPTION_ENABLED_2_RP = text_fr[281],
DEVOLVER_COMPRA_TITLE = text_fr[282],
DEVOLVER_COMPRA_DESC = text_fr[283],
SE_DETECTO_INFO = text_fr[284],
SE_DETECTO_2_INFO = text_fr[285],
AMMOUNT_OVERRIDE_ERROR = text_fr[286],
INFO_ALERT_TIME = text_fr[287],
INFO_ALERT_2_TIME = text_fr[288],

INFO_AMMOUNT_SPEND_DETECTED = text_fr[289],
INFO_AMMOUNT_SPEND2_DETECTED  = text_fr[290],
SEEMS_MESSAGE = text_fr[291],
REFUND_SUCCESS = text_fr[292],
REFUND2_SUCCESS = text_fr[293],
IGNORE_SUGGESTED_TIME = text_fr[294],
IGNORE_SUGGESTED_TIME_DESC = text_fr[295]

    }

}

